In [1]:
import pandas as pd
import warnings

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import nltk 
from nltk.stem import WordNetLemmatizer # to lemmatize the words
from nltk.tokenize import word_tokenize # to tokenize the words
from nltk.corpus import wordnet # to get the wordnet pos tags
from nltk.corpus import stopwords # to remove the stopwords
from sklearn.feature_extraction.text import CountVectorizer # to create a bag of words

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/martakarnaschodkiewicz/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
train_data = pd.read_csv('training_data.csv')

In [4]:
train_data.head()

  0\tdonald trump sends out embarrassing new year‚s eve message; this is disturbing
0  0\tdrunk bragging trump staffer started russia...
1  0\tsheriff david clarke becomes an internet jo...
2  0\ttrump is so obsessed he even has obama‚s na...
3  0\tpope francis just called out donald trump d...
4  0\tracist alabama cops brutalize black boy whi...

In [5]:
columns = ['label', 'headline']
train_data = pd.read_csv('training_data.csv', sep='\t', header=None, names=columns)

print(train_data.head())

   label                                           headline
0      0  donald trump sends out embarrassing new year‚s...
1      0  drunk bragging trump staffer started russian c...
2      0  sheriff david clarke becomes an internet joke ...
3      0  trump is so obsessed he even has obama‚s name ...
4      0  pope francis just called out donald trump duri...

In [6]:
train_data['headline'] = train_data['headline'].str.strip()

In [7]:
print(train_data.head())

   label                                           headline
0      0  donald trump sends out embarrassing new year‚s...
1      0  drunk bragging trump staffer started russian c...
2      0  sheriff david clarke becomes an internet joke ...
3      0  trump is so obsessed he even has obama‚s name ...
4      0  pope francis just called out donald trump duri...

In [8]:
train_data['headline'] = train_data['headline'].replace("[^a-zA-Z]", " ", regex=True)

In [9]:
# Doing x,y split on training data
X = train_data['headline']
y= train_data['label']

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Convert text data to numerical features using TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Train the classifier on the training data
rf_classifier.fit(X_train_tfidf, y_train)

RandomForestClassifier()

In [10]:



# Make predictions on the test data
y_test_pred = rf_classifier.predict(X_test_tfidf)
print("Training Data Classification Report:")
print(classification_report(y_test, y_test_pred))
print("Training Data Accuracy Score:", accuracy_score(y_test, y_test_pred))

Training Data Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      3529
           1       0.92      0.94      0.93      3302

    accuracy                           0.94      6831
   macro avg       0.94      0.94      0.94      6831
weighted avg       0.94      0.94      0.94      6831

Training Data Accuracy Score: 0.9354413702239789

In [11]:
data = pd.read_csv('training_data.csv')

In [12]:
columns = ['label', 'headline']
data = pd.read_csv('training_data.csv', sep='\t', header=None, names=columns)

print(data.head())

   label                                           headline
0      0  donald trump sends out embarrassing new year‚s...
1      0  drunk bragging trump staffer started russian c...
2      0  sheriff david clarke becomes an internet joke ...
3      0  trump is so obsessed he even has obama‚s name ...
4      0  pope francis just called out donald trump duri...

In [13]:
data['headline'].dtypes

dtype('O')

In [14]:
data['headline'] = data['headline'].str.strip()

In [15]:
nltk.download('punkt', download_dir='/tmp/nltk_data')

[nltk_data] Downloading package punkt to /tmp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [16]:
import os
os.environ['NLTK_DATA'] = '/tmp/nltk_data'
os.listdir('/tmp/nltk_data/tokenizers')

['punkt', 'punkt.zip']

In [17]:
data['headline'] = list(data['headline'])

In [18]:
data.shape

(34152, 2)

In [19]:
X = data['headline']
y = data['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
# Initialize the tokenizer
tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')

In [21]:
X_train = [[word.lower() for word in tokenizer.tokenize(i)] for i in X_train]
X_train

[['so'],
 ['final',
  'reckoning',
  'approaches',
  'for',
  'obama',
  's',
  'high',
  'court',
  'nominee'],
 ['illinois', 'budget', 'talks', 'fizzle', 'amid', 'partisan', 'entrenchment'],
 ['clinton',
  'spokesman',
  'ig',
  'report',
  'shows',
  'no',
  'clinton',
  'missteps',
  'on',
  'emails'],
 ['busted',
  'nancy',
  'pelosi',
  'claims',
  'no',
  'meeting',
  'with',
  'russian',
  'ambassador',
  'photo',
  'from',
  '2010',
  'proves',
  'otherwise',
  'video'],
 ['heartwarming',
  'hugs',
  'and',
  'kisses',
  'from',
  'potus',
  'during',
  'texas',
  'visit',
  'video'],
 ['hillary',
  'clinton',
  's',
  'battle',
  'plan',
  'use',
  'her',
  'sex',
  'offender',
  'husband',
  'and',
  'slimy',
  'racist',
  'barack',
  'obama',
  'as',
  'her',
  'attack',
  'dogs'],
 ['radical',
  'ny',
  'attorney',
  'general',
  'cracking',
  'down',
  'on',
  'conservatism',
  'working',
  'to',
  'make',
  'opposing',
  'the',
  'left',
  'a',
  'crime'],
 ['obama', 'blames', 'russia', 'for', 'hillary', 's', 'loss'],
 ['factbox',
  'one',
  'planet',
  'summit',
  'turns',
  'to',
  'private',
  'sector',
  'for',
  'climate',
  'action'],
 ['u',
  's',
  'senate',
  'votes',
  'near',
  'unanimously',
  'for',
  'russia',
  'iran',
  'sanctions'],
 ['green',
  'party',
  'dolt',
  'struggles',
  'to',
  'explain',
  'wisconsin',
  'election',
  'recount',
  'video'],
 ['zimbabwe',
  'minister',
  'moyo',
  's',
  'twitter',
  'account',
  'hacked',
  'family',
  'member'],
 ['wikileaks',
  'exposes',
  'clinton',
  'campaign',
  'in',
  'cahoots',
  'with',
  'corrupt',
  'doj',
  'on',
  'email',
  'scandal'],
 ['texas',
  'governor',
  'approves',
  'adoption',
  'bill',
  'that',
  'critics',
  'contend',
  'discriminates'],
 ['trump', 'rips', 'sessions', 'over', 'russia'],
 ['net',
  'neutrality',
  'repeal',
  'gives',
  'democrats',
  'fresh',
  'way',
  'to',
  'reach',
  'millennials'],
 ['nbc', 'gets', 'brutal', 'with', 'donald', 'trump'],
 ['state',
  'department',
  'will',
  'implement',
  'travel',
  'ban',
  'in',
  'orderly',
  'fashion',
  'spokeswoman'],
 ['congo', 'sets', 'presidential', 'election', 'for', 'december', '2018'],
 ['new',
  'york',
  'welfare',
  'programs',
  'more',
  'generous',
  'than',
  'sweden',
  'or',
  'france'],
 ['hands',
  'on',
  'dhs',
  'secretary',
  'john',
  'kelly',
  'tours',
  'border',
  'stunned',
  'that',
  'local',
  'officials',
  'harboring',
  'criminal',
  'illegals',
  'video'],
 ['u',
  's',
  'lawmakers',
  'reintroduce',
  'bill',
  'to',
  'end',
  'restrictions',
  'on',
  'cuba',
  'travel'],
 ['conservatives',
  'throw',
  'racist',
  'hissy',
  'fit',
  'because',
  'malia',
  'obama',
  'acted',
  'like',
  'a',
  'teenager',
  'at',
  'concert'],
 ['ivanka', 'trump', 'shares', 'famous', 'jewish', 'quote'],
 ['uk',
  's',
  'johnson',
  'makes',
  'fuller',
  'apology',
  'for',
  'remarks',
  'on',
  'jailed',
  'aid',
  'worker',
  'in',
  'iran'],
 ['in',
  'republican',
  'state',
  'obama',
  'talks',
  'with',
  'worried',
  'american',
  'mom'],
 ['russia',
  'will',
  'keep',
  'bases',
  'in',
  'syria',
  'to',
  'strike',
  'at',
  'insurgents',
  'kremlin'],
 ['major', 'study', 'finds', 'marijuana', 'perfectly', 'safe', 'for', 'teens'],
 ['trump',
  'picks',
  'boeing',
  'executive',
  'shanahan',
  'to',
  'become',
  'pentagon',
  's',
  'no',
  '2'],
 ['oops',
  'sheila',
  'jackson',
  'lee',
  'called',
  'the',
  'woman',
  'she',
  'kicked',
  'out',
  'of',
  'first',
  'class',
  'a',
  'racist',
  'too',
  'bad',
  'she',
  'didn',
  't',
  'know',
  'this',
  'one',
  'important',
  'thing',
  'about',
  'the',
  'passenger'],
 ['breaking',
  'obama',
  's',
  'director',
  'of',
  'diversity',
  'donates',
  'hundreds',
  'of',
  'thousands',
  'of',
  'tax',
  'payer',
  'dollars',
  'to',
  'open',
  'borders'],
 ['warning',
  'feds',
  'predict',
  '30',
  'trillion',
  'dollar',
  'debt',
  'because',
  'of',
  'these',
  'two',
  'key',
  'things'],
 ['trump',
  'caught',
  'paying',
  'women',
  'working',
  'on',
  'his',
  'campaign',
  'much',
  'less',
  'than',
  'men'],
 ['window',
  'closing',
  'for',
  'republican',
  'stealth',
  'assault',
  'on',
  'u',
  's',
  'regulations'],
 ['moscow',
  'u',
  's',
  'arms',
  'may',
  'spur',
  'use',
  'of',
  'force',
  'by',
  'kiev',
  'in',
  'eastern',
  'ukraine'],
 ['puerto',
  'rico',
  'creditors',
  'trade',
  'barbs',
  'over',
  'debt',
  'freeze',
  'bill'],
 ['report',
  'trump',
  'tried',
  'to',
  'pull',
  'his',
  'own',
  'saturday',
  'night',
  'massacre'],
 ['hannity',
  'loses',
  'his',
  'sh',
  't',
  'after',
  'social',
  'media',
  'pounds',
  'his',
  'racist',
  'offer',
  'to',
  'send',
  'obamas',
  'to',
  'africa'],
 ['woman',
  'receives',
  'death',
  'threats',
  'after',
  'photo',
  'of',
  'her',
  'at',
  'sanders',
  'rally',
  'goes',
  'viral',
  'video',
  'tweets'],
 ['irish',
  'border',
  'should',
  'see',
  'no',
  'queues',
  'post',
  'brexit',
  'british',
  'minister'],
 ['third',
  'grader',
  'roasts',
  'trump',
  'with',
  'hilarious',
  'letter',
  'obliterating',
  'his',
  'deportation',
  'rhetoric',
  'image'],
 ['spain',
  's',
  'crisis',
  're',
  'ignited',
  'as',
  'catalan',
  'separatists',
  'win',
  'vote'],
 ['leading',
  'democrat',
  'critics',
  'can',
  't',
  'conclude',
  'trump',
  'is',
  'impaired'],
 ['trump',
  's',
  'views',
  'on',
  'china',
  's',
  'handling',
  'of',
  'tiananmen',
  'square',
  'will',
  'make',
  'you',
  'despise',
  'him',
  'even',
  'more'],
 ['china',
  'pakistan',
  'to',
  'look',
  'at',
  'including',
  'afghanistan',
  'in',
  '57',
  'billion',
  'economic',
  'corridor'],
 ['trump',
  'urges',
  'india',
  's',
  'modi',
  'to',
  'fix',
  'deficit',
  'but',
  'stresses',
  'strong',
  'ties'],
 ['u',
  's',
  'appeals',
  'court',
  'revives',
  'claims',
  'in',
  '1',
  '7',
  'billion',
  'iran',
  'terrorism',
  'lawsuit'],
 ['breaking',
  'liberal',
  'media',
  's',
  'worst',
  'nightmare',
  'comes',
  'true',
  'kellyanne',
  'conway',
  'lands',
  'top',
  'position',
  'on',
  'trump',
  's',
  'team'],
 ['trump',
  'uk',
  's',
  'may',
  'talk',
  'middle',
  'east',
  'peace',
  'white',
  'house'],
 ['white',
  'house',
  'rebuts',
  'supreme',
  'court',
  'hypocrisy',
  'charge',
  'against',
  'obama'],
 ['breaking',
  'a',
  'huge',
  'deal',
  'putin',
  'suspends',
  'nuclear',
  'pact',
  'with',
  'us'],
 ['video',
  'flashback',
  'martin',
  'luther',
  'king',
  'jr',
  'on',
  'riots',
  'we',
  'can',
  't',
  'win',
  'a',
  'violent',
  'revolution'],
 ['czech',
  'election',
  'winner',
  'babis',
  'meets',
  'anti',
  'eu',
  'party',
  'in',
  'hunt',
  'for',
  'viable',
  'government'],
 ['melissa',
  'mccarthy',
  'just',
  'took',
  'on',
  'sean',
  'spicer',
  's',
  'hitler',
  'moment',
  'and',
  'it',
  's',
  'f',
  'cking',
  'perfect',
  'video'],
 ['media',
  'critic',
  'destroys',
  'cnn',
  'for',
  'hiring',
  'trump',
  's',
  'campaign',
  'manager'],
 ['boom',
  'dr',
  'alveda',
  'king',
  'scolds',
  'sen',
  'liz',
  'warren',
  'we',
  'won',
  't',
  'accept',
  'racist',
  'bait',
  'and',
  'switch',
  'video'],
 ['truth',
  'donald',
  'trump',
  'clinton',
  'created',
  'isis',
  'with',
  'obama',
  'video'],
 ['cnn',
  'interview',
  'turns',
  'into',
  'screaming',
  'match',
  'when',
  'activist',
  'director',
  'argues',
  'new',
  'irrelevant',
  'footage',
  'of',
  'michael',
  'brown',
  'is',
  'game',
  'changer',
  'video'],
 ['house',
  'votes',
  'to',
  'bar',
  'heavy',
  'water',
  'purchases',
  'from',
  'iran'],
 ['senate',
  'aims',
  'for',
  'a',
  'skinny',
  'obamacare',
  'repeal',
  'as',
  'other',
  'options',
  'fail'],
 ['cnn',
  'host',
  'stuns',
  'sean',
  'spicer',
  'with',
  'an',
  'onslaught',
  'of',
  'facts',
  'about',
  'obamacare',
  'repeal',
  'video'],
 ['american',
  'liar',
  'wingnut',
  'icon',
  'chris',
  'kyle',
  'wasn',
  't',
  'the',
  'hero',
  'he',
  'made',
  'himself',
  'out',
  'to',
  'be'],
 ['obama',
  'touts',
  'supreme',
  'court',
  'choice',
  'as',
  'symbol',
  'of',
  'fair',
  'mindedness'],
 ['illinois',
  'entire',
  'team',
  'of',
  '8',
  'yr',
  'old',
  'kids',
  'perform',
  'disgusting',
  'act',
  'of',
  'disrespect',
  'for',
  'our',
  'flag',
  'and',
  'law',
  'enforcement',
  'under',
  'guidance',
  'of',
  'coach'],
 ['trump',
  'tweet',
  'attacking',
  'clinton',
  'employs',
  'image',
  'of',
  'jewish',
  'star'],
 ['drain',
  'the',
  'swamp',
  'republicans',
  'not',
  'running',
  'for',
  're',
  'election',
  'in',
  '2018'],
 ['paul',
  'manafort',
  'trump',
  's',
  'former',
  'campaign',
  'chief',
  'drops',
  'legal',
  'team'],
 ['democrats',
  'flex',
  'muscles',
  'as',
  'congress',
  'confronts',
  'a',
  'government',
  'shutdown'],
 ['u',
  's',
  'lawmakers',
  'aim',
  'to',
  'comply',
  'with',
  'iran',
  'nuclear',
  'deal',
  'eu'],
 ['eu',
  's',
  'barnier',
  'is',
  'ready',
  'to',
  'speed',
  'up',
  'brexit',
  'negotiations'],
 ['trump',
  'says',
  'he',
  'will',
  'negotiate',
  'with',
  'democrats',
  'on',
  'healthcare'],
 ['russian',
  'parliament',
  'speaker',
  'says',
  'hopes',
  'for',
  'better',
  'ties',
  'with',
  'u',
  's'],
 ['hillary',
  'pays',
  'professional',
  'trolls',
  '1',
  'million',
  'to',
  'make',
  'her',
  'look',
  'popular',
  'on',
  'social',
  'media'],
 ['house',
  'panel',
  'okays',
  'dodd',
  'frank',
  'revamp',
  'amid',
  'partisan',
  'rancor'],
 ['nigeria',
  's',
  'buhari',
  'to',
  'visit',
  'heartland',
  'of',
  'biafra',
  'secessionists'],
 ['trump',
  'tries',
  'shaming',
  'nfl',
  'with',
  'video',
  'of',
  'hockey',
  'fans',
  'standing',
  'for',
  'anthem',
  'and',
  'humiliates',
  'himself'],
 ['algeria',
  's',
  'ruling',
  'parties',
  'retain',
  'majority',
  'in',
  'local',
  'elections'],
 ['russia',
  'says',
  'google',
  'down',
  'ranking',
  'sputnik',
  'rt',
  'would',
  'be',
  'censorship'],
 ['top',
  'tech',
  'official',
  'at',
  'hacked',
  'u',
  's',
  'personnel',
  'agency',
  'retires',
  'under',
  'pressure'],
 ['kerry',
  'says',
  'u',
  's',
  'and',
  'venezuela',
  'agree',
  'to',
  'start',
  'talks',
  'to',
  'ease',
  'tensions'],
 ['clinton',
  's',
  'lead',
  'over',
  'trump',
  'narrows',
  'to',
  'less',
  'than',
  'three',
  'points',
  'reuters',
  'ipsos',
  'poll'],
 ['newsweek',
  'outs',
  'trump',
  'as',
  'putin',
  's',
  'puppet',
  'and',
  'our',
  'nato',
  'allies',
  'are',
  'terrified',
  'video'],
 ['cruz',
  's',
  'desperate',
  'last',
  'minute',
  'attempt',
  'to',
  'win',
  'iowa',
  'is',
  'so',
  'vile',
  'state',
  'officials',
  'just',
  'nailed',
  'him',
  'for',
  'it'],
 ['meet',
  'the',
  'cowardly',
  'republicans',
  'who',
  're',
  'endorsed',
  'trump',
  'after',
  'condemning',
  'him',
  'for',
  'sexual',
  'assault'],
 ['trump',
  'to',
  'unveil',
  'new',
  'responses',
  'to',
  'iranian',
  'bad',
  'behavior',
  'white',
  'house'],
 ['wow',
  'sarcastic',
  'mike',
  'barnicle',
  'gets',
  'an',
  'earful',
  'from',
  'kellyanne',
  'conway',
  'for',
  'saying',
  'republicans',
  'weren',
  't',
  'fair',
  'to',
  'obama',
  'video'],
 ['lebanon', 'pm', 'hariri', 'resigns', 'assails', 'iran', 'and', 'hezbollah'],
 ['awesome',
  'reporter',
  'ruins',
  'trump',
  'protester',
  's',
  'day',
  'with',
  'this',
  'shocking',
  'news',
  'video'],
 ['obama',
  'administration',
  'denies',
  'iran',
  'cash',
  'payment',
  'was',
  'a',
  'ransom'],
 ['hilarious',
  'video',
  'shows',
  'the',
  'moment',
  'bernie',
  'discovered',
  'he',
  's',
  'related',
  'to',
  'his',
  'snl',
  'impersonator'],
 ['mccain',
  'introduces',
  'bill',
  'to',
  'kill',
  'puerto',
  'rico',
  'shipping',
  'restrictions'],
 ['trump',
  'tells',
  'thousands',
  'at',
  'fl',
  'rally',
  'barack',
  'hussein',
  'obama',
  'is',
  'founder',
  'of',
  'isis',
  'hillary',
  'is',
  'co',
  'founder',
  'video'],
 ['ouch',
  'the',
  'left',
  's',
  'other',
  'woman',
  'just',
  'landed',
  'a',
  'direct',
  'hit',
  'on',
  'hillary',
  'and',
  'she',
  'is',
  'spot',
  'on'],
 ['president',
  'promotes',
  'made',
  'in',
  'america',
  'omaha',
  'steaks',
  'owner',
  'wanted',
  'to',
  'kiss',
  'me',
  'for',
  'reopening',
  'trade',
  'with',
  'china',
  'video'],
 ['here',
  'we',
  'go',
  'again',
  'trump',
  'supporters',
  'beat',
  'the',
  'sh',
  't',
  'out',
  'of',
  'protester',
  'video'],
 ['basketball',
  'legend',
  'bobby',
  'knight',
  'tells',
  'judge',
  'jeanine',
  'why',
  'he',
  'endorsed',
  'trump',
  'video'],
 ['breaking', 'why', 'did', 'obama', 'just', 'break', 'democrat', 'ranks'],
 ['why',
  'did',
  'the',
  'state',
  'department',
  'redact',
  'this',
  'one',
  'clinton',
  'sentence'],
 ['gop', 'governor', 'blocks', 'minimum', 'wage', 'increase'],
 ['a',
  'must',
  'see',
  'the',
  'baltimore',
  'riot',
  'story',
  'in',
  'one',
  'big',
  'picture'],
 ['trump',
  's',
  'opposition',
  'to',
  'trade',
  'deals',
  'fuels',
  'internal',
  'party',
  'opposition'],
 ['senate',
  'republican',
  'says',
  'dumpster',
  'fires',
  'are',
  'more',
  'popular',
  'than',
  'trump'],
 ['kimberly',
  'guilfoyle',
  'serious',
  'legal',
  'issues',
  'surround',
  'rachel',
  'maddow',
  'report',
  'on',
  'trump',
  's',
  '2005',
  'tax',
  'return',
  'video'],
 ['video',
  'harlem',
  'bar',
  'kicks',
  'customers',
  'out',
  'for',
  'wearing',
  'trump',
  'hats',
  'we',
  'don',
  't',
  'play',
  'that',
  'sh',
  't',
  'here'],
 ['this',
  'is',
  'proof',
  'that',
  'donald',
  'trump',
  'may',
  'be',
  'the',
  'worst',
  'money',
  'manager',
  'in',
  'the',
  'campaign',
  'video'],
 ['watch',
  'female',
  'hispanic',
  'cop',
  's',
  'all',
  'lives',
  'matter',
  'viral',
  'video',
  'message',
  'i',
  'may',
  'get',
  'in',
  'trouble',
  'for',
  'doing',
  'this'],
 ['borussia',
  'dortmund',
  'bomb',
  'suspect',
  'stands',
  'trial',
  'for',
  'attempted',
  'murder'],
 ['flashback',
  'video',
  'jesse',
  'jackson',
  'praises',
  'donald',
  'trump',
  'for',
  'his',
  'commitment',
  'to',
  'bringing',
  'blacks'],
 ['daniel',
  'greenfield',
  'nails',
  'it',
  'america',
  'is',
  'being',
  'run',
  'just',
  'like',
  'baltimore'],
 ['palestinian',
  'billionaire',
  'masri',
  'detained',
  'in',
  'saudi',
  'arabia',
  'sources'],
 ['top',
  'u',
  's',
  'diplomat',
  'role',
  'an',
  'unlikely',
  'fit',
  'for',
  'tough',
  'guy',
  'giuliani'],
 ['spacex', 'to', 'launch', 'turkish', 'satellites', 'minister', 'says'],
 ['cannot',
  'be',
  'complacent',
  'about',
  'potential',
  'threat',
  'of',
  'north',
  'korean',
  'missiles',
  'uk',
  'minister'],
 ['u',
  's',
  'voters',
  'want',
  'leader',
  'to',
  'end',
  'advantage',
  'of',
  'rich',
  'and',
  'powerful',
  'reuters',
  'ipsos',
  'poll'],
 ['al',
  'gore',
  'tells',
  'bill',
  'maher',
  'get',
  'rid',
  'of',
  'electoral',
  'college'],
 ['macron',
  'taps',
  'author',
  'slimani',
  'as',
  'french',
  'language',
  'emissary'],
 ['nigeria',
  'says',
  'u',
  's',
  'agrees',
  'delayed',
  '593',
  'million',
  'fighter',
  'plane',
  'sale'],
 ['thailand',
  'prime',
  'minister',
  'to',
  'visit',
  'white',
  'house',
  'on',
  'october',
  '3'],
 ['north',
  'carolina',
  'transgender',
  'bathroom',
  'law',
  'faces',
  'federal',
  'court',
  'test'],
 ['melania',
  'has',
  'to',
  'remind',
  'trump',
  'how',
  'to',
  'do',
  'national',
  'anthem',
  'in',
  'most',
  'pathetic',
  'moment',
  'of',
  'wh',
  'easter',
  'video'],
 ['thanks',
  'obama',
  'the',
  '99',
  'percent',
  'are',
  'doing',
  'better',
  'than',
  'in',
  '17',
  'years'],
 ['u',
  's',
  'did',
  'not',
  'forewarn',
  'eu',
  'on',
  'climate',
  'deal',
  'spokeswoman'],
 ['british',
  'foreign',
  'secretary',
  'concerned',
  'about',
  'planned',
  'u',
  's',
  'recognition',
  'of',
  'jerusalem'],
 ['milestones', 'in', 'legal', 'fight', 'over', 'texas', 'abortion', 'law'],
 ['loss',
  'of',
  'march',
  'madness',
  'games',
  'could',
  'hurt',
  'north',
  'carolina',
  'governor',
  's',
  're',
  'election',
  'bid'],
 ['don',
  't',
  'count',
  'on',
  'germany',
  's',
  'spd',
  'to',
  'rescue',
  'macron',
  's',
  'euro',
  'agenda'],
 ['jeb',
  'bush',
  'kicks',
  'off',
  'gop',
  'convention',
  'by',
  'going',
  'full',
  'nevertrump'],
 ['former',
  'u',
  's',
  'officials',
  'to',
  'testify',
  'at',
  'may',
  '8',
  'senate',
  'hearing',
  'on',
  'russia',
  'probe'],
 ['long',
  'a',
  'rival',
  'ted',
  'cruz',
  'endorses',
  'trump',
  'in',
  'u',
  's',
  'presidential',
  'race'],
 ['judge',
  'jeanine',
  'pirro',
  'we',
  're',
  'tired',
  'of',
  'being',
  'lectured',
  'to',
  'by',
  'the',
  'fat',
  'cats',
  'in',
  'washington',
  'video'],
 ['china',
  'says',
  'it',
  'will',
  'make',
  'efforts',
  'on',
  'syria',
  'reconstruction'],
 ['game',
  'changer',
  'trump',
  'recruits',
  'election',
  'observers',
  'to',
  'prevent',
  'election',
  'rigging',
  'by',
  'crooked',
  'hillary'],
 ['just',
  'in',
  'wapo',
  'reporter',
  'who',
  'broke',
  'news',
  'on',
  'judge',
  'roy',
  'moore',
  'story',
  'has',
  'a',
  'criminal',
  'history',
  'of',
  'faking'],
 ['clown',
  'show',
  'former',
  'cia',
  'official',
  'takes',
  'shots',
  'at',
  'trump',
  's',
  'team',
  'in',
  'hilarious',
  'clip',
  'video'],
 ['oregon', 'militant', 'flips', 'over', 'his', 'vehicle'],
 ['megyn',
  'kelly',
  'reveals',
  'the',
  'creepy',
  'way',
  'donald',
  'trump',
  'tried',
  'to',
  'woo',
  'her',
  'image'],
 ['trump',
  'sends',
  'out',
  'email',
  'begging',
  'supporters',
  'to',
  'send',
  'him',
  'money',
  'to',
  'defend',
  'against',
  'his',
  'scandals'],
 ['radical', 'tolerant', 'female', 'antifa'],
 ['persecuted', 'rohingya', 'muslims', 'flee', 'violence', 'in', 'myanmar'],
 ['u',
  's',
  'diplomat',
  'nuland',
  'says',
  'optimistic',
  'about',
  'ukraine',
  'reforms'],
 ['not',
  'racist',
  'trump',
  'fan',
  'goes',
  'on',
  'hours',
  'long',
  'twitter',
  'rant',
  'about',
  'nigs',
  'and',
  'obamaphones',
  'tweets'],
 ['putz',
  'obama',
  'calls',
  'electoral',
  'college',
  'a',
  'vestige',
  'of',
  'an',
  'earlier',
  'time',
  'in',
  'america'],
 ['democrat',
  'hilariously',
  'mocks',
  'paul',
  'ryan',
  'during',
  'house',
  'sit',
  'in',
  'he',
  's',
  'up',
  'in',
  'his',
  'office',
  'crying',
  'video'],
 ['democrats',
  'seek',
  'probe',
  'of',
  'trump',
  'donation',
  'to',
  'florida',
  'attorney',
  'general'],
 ['bernie',
  'sanders',
  'draws',
  'impressive',
  'crowd',
  'at',
  'pine',
  'ridge',
  'reservation',
  'video'],
 ['trump',
  'livid',
  'after',
  'legit',
  'national',
  'poll',
  'gives',
  'him',
  'a',
  'reality',
  'check',
  'images'],
 ['outrage',
  'and',
  'desperation',
  'video',
  'captures',
  'american',
  'company',
  'telling',
  '1400',
  'workers',
  'their',
  'jobs',
  'are',
  'going',
  'to',
  'mexico'],
 ['elections',
  'official',
  'asks',
  'trump',
  'for',
  'evidence',
  'of',
  'voter',
  'fraud'],
 ['twitter',
  'f',
  'cks',
  'trump',
  'up',
  'after',
  'he',
  'says',
  'senators',
  'who',
  'oppose',
  'muslim',
  'ban',
  'are',
  'trying',
  'to',
  'start',
  'world',
  'war',
  'iii',
  'tweets'],
 ['trey',
  'gowdy',
  'scorches',
  'hillary',
  'clinton',
  'in',
  'his',
  'opening',
  'statement',
  'at',
  'benghazi',
  'hearings',
  'video'],
 ['dnc',
  'insiders',
  'vote',
  'to',
  'take',
  'bernie',
  's',
  'win',
  'in',
  'new',

In [22]:
X_test = [[word.lower() for word in tokenizer.tokenize(i)] for i in X_test]
X_test

[['release', 'of', 'house', 'tax', 'bill', 'delayed', 'until', 'thursday'],
 ['confusion',
  'over',
  'trump',
  's',
  'first',
  'talks',
  'with',
  'foreign',
  'leader'],
 ['obama',
  'says',
  'chinese',
  'led',
  'trade',
  'deal',
  'shows',
  'need',
  'for',
  'tpp',
  'washington',
  'post'],
 ['former', 'pastor', 'turned', 'teacher', 'beat', 'students'],
 ['breaking',
  'south',
  'carolina',
  'senate',
  'caves',
  'votes',
  'to',
  'remove',
  'confederate',
  'flag',
  'from',
  'statehouse',
  'grounds',
  'because',
  'it',
  's',
  'all',
  'about',
  'the',
  'flag'],
 ['austria',
  's',
  'far',
  'right',
  'freedom',
  'party',
  'congratulates',
  'trump'],
 ['canada',
  'mexico',
  'vow',
  'to',
  'stick',
  'with',
  'nafta',
  'talks',
  'mexico',
  'works',
  'on',
  'plan',
  'b'],
 ['bill',
  'maher',
  'hilariously',
  'torches',
  'whiny',
  'trump',
  's',
  'debate',
  'meltdown'],
 ['italy',
  's',
  'populist',
  '5',
  'star',
  'strengthens',
  'lead',
  'after',
  'sicily',
  'vote',
  'poll'],
 ['was',
  'murdered',
  '27',
  'year',
  'old',
  'democrat',
  'operative',
  'about',
  'to',
  'blow',
  'the',
  'whistle',
  'on',
  'voter',
  'fraud',
  'when',
  'he',
  'was',
  'shot',
  'in',
  'the',
  'back',
  'video'],
 ['teens',
  'get',
  'creeped',
  'out',
  'when',
  'republican',
  'lawmaker',
  'asks',
  'if',
  'they',
  'are',
  'virgins',
  'during',
  'statehouse',
  'visit'],
 ['in', 'your', 'face', 'following', 'obama', 's', 'gun', 'control', 'rally'],
 ['obama', 'tells', 'gop', 'to', 'f', 'ck', 'off'],
 ['watch',
  'how',
  'moderate',
  'american',
  'muslims',
  'respond',
  'when',
  'asked',
  'if',
  'they',
  'prefer',
  'us',
  'or',
  'sharia',
  'law'],
 ['trump',
  'retweets',
  'hilarious',
  'video',
  'of',
  'him',
  'hitting',
  'golf',
  'ball',
  'that',
  'hits',
  'crooked',
  'hillary',
  'in',
  'the',
  'head',
  'left',
  'goes',
  'nuts'],
 ['may',
  'will',
  'allow',
  'brexit',
  'delay',
  'in',
  'exceptional',
  'circumstances'],
 ['clinton',
  'to',
  'accuse',
  'trump',
  'of',
  'embracing',
  'nativist',
  'political',
  'movement'],
 ['trump',
  'freaking',
  'out',
  'over',
  'the',
  'port',
  'a',
  'potties',
  'at',
  'inauguration',
  'for',
  'the',
  'dumbest',
  'reason',
  'image'],
 ['tucker',
  'on',
  'comey',
  's',
  'firing',
  'dictatorship',
  'by',
  'the',
  'unelected',
  'that',
  's',
  'the',
  'real',
  'danger',
  'video'],
 ['about',
  'time',
  'christian',
  'group',
  'sues',
  'amazon',
  'and',
  'splc',
  'for',
  'designation',
  'as',
  'hate',
  'group'],
 ['why',
  '93',
  'yr',
  'old',
  'woman',
  'voted',
  'for',
  'the',
  'first',
  'time',
  'in',
  'her',
  'life',
  'for',
  'trump'],
 ['federal',
  'court',
  'strikes',
  'down',
  'racist',
  'texas',
  'voter',
  'id',
  'law'],
 ['ellen',
  'degeneres',
  'refuses',
  'to',
  'have',
  'donald',
  'trump',
  'on',
  'her',
  'show',
  'here',
  's',
  'why',
  'video'],
 ['trump',
  'hires',
  'son',
  's',
  'wedding',
  'planner',
  'to',
  'run',
  'new',
  'york',
  'housing',
  'department'],
 ['at',
  'least',
  '800',
  'civilians',
  'killed',
  'by',
  'coalition',
  'strikes',
  'in',
  'iraq',
  'syria',
  'report'],
 ['china',
  'says',
  'confident',
  'in',
  'economic',
  'relations',
  'with',
  'u',
  's',
  'ahead',
  'of',
  'trump',
  'visit'],
 ['jesse',
  'watters',
  'like',
  'you',
  've',
  'never',
  'seen',
  'him',
  'before',
  'watch',
  'him',
  'rip',
  'into',
  'juan',
  'williams',
  'over',
  'calling',
  'trump',
  'family',
  'unpatriotic',
  'schools',
  'him',
  'on',
  'corrupt',
  'democratic',
  'party',
  'ties',
  'to',
  'communism'],
 ['barracuda',
  'former',
  'obama',
  'advisor',
  'rants',
  'against',
  'trump',
  'for',
  'keeping',
  'campaign',
  'promises',
  'video'],
 ['vast',
  'majority',
  'of',
  'suspects',
  'in',
  'graft',
  'probe',
  'agreeing',
  'to',
  'settle',
  'crown',
  'prince',
  'says'],
 ['trump',
  's',
  'trying',
  'to',
  'attend',
  'muhammad',
  'ali',
  's',
  'muslim',
  'funeral',
  'his',
  'family',
  's',
  'response',
  'is',
  'brilliant'],
 ['wikileaks',
  'smoking',
  'gun',
  'here',
  's',
  'best',
  'proof',
  'hillary',
  'is',
  'just',
  'a',
  'puppet',
  'for',
  'globalist',
  'george',
  'soros'],
 ['warren',
  'kaine',
  'castro',
  'on',
  'clinton',
  'running',
  'mate',
  'short',
  'list',
  'ap'],
 ['aide',
  'tries',
  'to',
  'refocus',
  'u',
  's',
  'tax',
  'debate',
  'after',
  'trump',
  's',
  'corporate',
  'rate',
  'remark'],
 ['karma',
  'birthday',
  'boy',
  'bill',
  'clinton',
  'heckled',
  'by',
  'kids',
  'on',
  'the',
  'golf',
  'course'],
 ['facing', 'tough', 're', 'election'],
 ['right',
  'wing',
  'extremist',
  'tries',
  'to',
  'repeat',
  'oklahoma',
  'city',
  'bombing',
  'as',
  'nazis',
  'terrorize',
  'charlottesville'],
 ['saudi',
  'arabia',
  'should',
  'not',
  'forfeit',
  'sovereign',
  'right',
  'to',
  'enrich',
  'uranium',
  'senior',
  'prince'],
 ['fights',
  'erupt',
  'at',
  'pro',
  'trump',
  'rally',
  'on',
  'california',
  'beach'],
 ['saudi',
  'businessman',
  'in',
  'debt',
  'dispute',
  'released',
  'from',
  'detention',
  'sources'],
 ['house',
  'leader',
  'says',
  'willing',
  'to',
  'do',
  'conference',
  'committee',
  'on',
  'healthcare'],
 ['puerto',
  'rico',
  'governor',
  'hopes',
  'for',
  'open',
  'dialogue',
  'with',
  'mnuchin'],
 ['out',
  'for',
  'votes',
  'battle',
  'over',
  'rights',
  'inspires',
  'more',
  'u',
  's',
  'transgender',
  'candidates'],
 ['laura',
  'ingraham',
  's',
  'brilliant',
  'idea',
  'on',
  'how',
  'to',
  'shake',
  'up',
  'liberal',
  'college',
  'campuses',
  'video'],
 ['in',
  'virginia',
  'clinton',
  'tests',
  'senator',
  'tim',
  'kaine',
  'as',
  'a',
  'safe',
  'vp',
  'pick'],
 ['democrats',
  'across',
  'the',
  'country',
  'are',
  'figuring',
  'out',
  'ways',
  'to',
  'force',
  'trump',
  'to',
  'release',
  'his',
  'tax',
  'returns'],
 ['fox',
  'anchor',
  'chris',
  'wallace',
  'rips',
  'nra',
  'stooge',
  'a',
  'new',
  'one',
  'for',
  'lying',
  'about',
  'gun',
  'control'],
 ['updated',
  'video',
  'is',
  'this',
  'america',
  'conservatives',
  'and',
  'their',
  'families',
  'experience',
  'shocking',
  'abuse',
  'and',
  'shaming',
  'in',
  'their',
  'homes',
  'ordered',
  'by',
  'leftist',
  'da',
  'as',
  'part',
  'of',
  'insane',
  'vendetta'],
 ['epic',
  'flashback',
  'megyn',
  'kelly',
  'destroyed',
  'by',
  'newt',
  'gingrich',
  'her',
  'predictions',
  'are',
  '100',
  'wrong',
  'video'],
 ['trump',
  'to',
  'make',
  'announcement',
  'on',
  'any',
  'comey',
  'tapes',
  'this',
  'week',
  'white',
  'house'],
 ['insane',
  'secret',
  'deal',
  'obama',
  'made',
  'with',
  'death',
  'to',
  'america',
  's',
  'iran',
  'includes',
  'iran',
  'monitoring',
  'their',
  'own',
  'nuclear',
  'sites'],
 ['exxon',
  'probe',
  'is',
  'unconstitutional',
  'republican',
  'prosecutors',
  'say'],
 ['china',
  'complains',
  'to',
  'australia',
  'over',
  'turnbull',
  'comments',
  'on',
  'interference'],
 ['dear', 'liberal'],
 ['epipen',
  'ceo',
  'under',
  'fire',
  'for',
  'price',
  'gouging',
  'is',
  'daughter',
  'of',
  'us',
  'senator'],
 ['samantha',
  'bee',
  'takes',
  'on',
  'the',
  'nra',
  'and',
  'its',
  'asinine',
  'mascot',
  'and',
  'it',
  'is',
  'glorious',
  'video'],
 ['obama',
  'to',
  'u',
  's',
  'military',
  'on',
  'putin',
  'he',
  'did',
  'not',
  'take',
  'my',
  'warnings',
  'on',
  'syria',
  'encourages',
  'russians',
  'to',
  'get',
  'a',
  'little',
  'smarter'],
 ['united',
  'nations',
  'chief',
  'very',
  'worried',
  'by',
  'saudi',
  'lebanon',
  'tensions'],
 ['kellyanne',
  'conway',
  'trump',
  'is',
  'gracious',
  'to',
  'not',
  'prosecute',
  'clinton',
  'while',
  'recount',
  'is',
  'underway',
  'video'],
 ['trump',
  'on',
  'twitter',
  'august',
  '8',
  'opioid',
  'crisis',
  'north',
  'korea'],
 ['u',
  's',
  'diplomat',
  'warns',
  'against',
  'isolationism',
  'in',
  'implicit',
  'trump',
  'rebuke'],
 ['right',
  'wing',
  'boogeyman',
  'george',
  'soros',
  'pops',
  'out',
  'to',
  'scare',
  'conservatives',
  'by',
  'calling',
  'out',
  'trump'],
 ['liberals',
  'freak',
  'out',
  'trump',
  'wipes',
  'out',
  'one',
  'of',
  'obama',
  's',
  'most',
  'controversial',
  'executive',
  'actions',
  'gives',
  'rights',
  'back',
  'to',
  'states',
  'video'],
 ['trump',
  's',
  'lawyer',
  'says',
  'trump',
  'has',
  'no',
  'russian',
  'income',
  'with',
  'a',
  'few',
  'exceptions'],
 ['moscow',
  'has',
  'never',
  'supported',
  'complete',
  'embargo',
  'on',
  'north',
  'korea',
  'ria',
  'cites',
  'deputy',
  'fm'],
 ['vp',
  'joe',
  'biden',
  'to',
  'make',
  'appearance',
  'at',
  'oscars',
  'to',
  'introduce',
  'song',
  'about',
  'sexual',
  'assault'],
 ['exclusive',
  'trump',
  'says',
  'republican',
  'border',
  'tax',
  'could',
  'boost',
  'u',
  's',
  'jobs'],
 ['lol',
  'un',
  'refugee',
  'spokes',
  'celebrity',
  'angelina',
  'jolie',
  'admonishes',
  'u',
  's',
  'for',
  'undermining',
  'international',
  'law',
  'by',
  'resisting',
  'flow',
  'of',
  'muslim',
  'refugees'],
 ['chad',
  'rejects',
  'u',
  's',
  'bribery',
  'allegations',
  'against',
  'president'],
 ['rip',
  'proud',
  'patriot',
  'marine',
  'dies',
  'after',
  'delivering',
  'powerful',
  'message',
  'to',
  'president',
  'trump'],
 ['chris',
  'wallace',
  'just',
  'shoved',
  'his',
  'foot',
  'so',
  'far',
  'up',
  'trump',
  's',
  'ass',
  'it',
  'came',
  'out',
  'his',
  'mouth',
  'video'],
 ['bernie',
  'sanders',
  'open',
  'to',
  'being',
  'clinton',
  's',
  'v',
  'p',
  'video'],
 ['facebook',
  'twitter',
  'support',
  'apple',
  'on',
  'encryption',
  'dispute',
  'with',
  'fbi'],
 ['poverty',
  'pimp',
  'al',
  'sharpton',
  'uses',
  'the',
  'bible',
  'to',
  'say',
  'dems',
  'should',
  'give',
  'the',
  'big',
  'payback',
  'to',
  'republicans'],
 ['kellyanne',
  'conway',
  'on',
  'trump',
  's',
  'terrorism',
  'policy',
  'we',
  'need',
  'more',
  'careful',
  'and',
  'extreme',
  'vetting',
  'video'],
 ['video',
  'american',
  'vet',
  'dies',
  'fighting',
  'isis',
  'couldn',
  't',
  'sit',
  'back',
  'and',
  'watch',
  'iraq',
  'being',
  'taken',
  'over',
  'by',
  'isis',
  'after',
  'his',
  'brothers',
  'shed',
  'their',
  'blood',
  'to',
  'make',
  'iraq',
  'free',
  'democracy'],
 ['oas',
  'says',
  'honduran',
  'vote',
  'results',
  'in',
  'doubt',
  'due',
  'to',
  'irregularities'],
 ['donald',
  'trump',
  's',
  'touching',
  'gesture',
  'after',
  'rally',
  'caught',
  'on',
  'video'],
 ['is',
  'a',
  'gop',
  'civil',
  'war',
  'coming',
  'rnc',
  'chair',
  'accidentally',
  'spoke',
  'the',
  'truth',
  'about',
  '2016',
  'nomination',
  'process'],
 ['unreal',
  'pro',
  'cuba',
  'travel',
  'at',
  'pbs',
  'and',
  'nbc',
  'cuba',
  'has',
  'so',
  'much',
  'going',
  'for',
  'it',
  'it',
  's',
  'proudly',
  'communist',
  'video'],
 ['britain',
  's',
  'may',
  'party',
  'leaders',
  'agree',
  'to',
  'tackle',
  'sexual',
  'harassment',
  'with',
  'new',
  'measures'],
 ['senator', 'wyden', 'pledges', 'to', 'fight', 'limits', 'on', 'encryption'],
 ['alabama',
  'attorney',
  'general',
  'named',
  'to',
  'jeff',
  'sessions',
  'senate',
  'seat'],
 ['families',
  'returning',
  'to',
  'ruined',
  'philippine',
  'city',
  'taught',
  'to',
  'identify',
  'bombs'],
 ['desperate',
  'lindsey',
  'graham',
  'calls',
  'clinton',
  'foundation',
  'controversy',
  'a',
  'gift',
  'from',
  'the',
  'political',
  'gods',
  'video'],
 ['trump', 'takes', 'credit', 'for', 'republican', 'win', 'in', 'georgia'],
 ['powerful',
  'moment',
  'between',
  'biden',
  'and',
  'protester',
  'ends',
  'up',
  'with',
  'invitation',
  'backstage',
  'video'],
 ['black',
  'leader',
  'calls',
  'on',
  'black',
  'caucus',
  'members',
  'to',
  'resign',
  'praises',
  'trump',
  's',
  'visit',
  'to',
  'detroit',
  'video'],
 ['millions',
  'of',
  'insecure',
  'gadgets',
  'exposed',
  'in',
  'european',
  'cities',
  'report'],
 ['democrats',
  'literally',
  'scream',
  'shame',
  'at',
  'republicans',
  'for',
  'blocking',
  'lgbt',
  'amendment',
  'video'],
 ['house', 'seeks', 'to', 'tighten', 'restrictions', 'on', 'pakistan', 'aid'],
 ['obamacare',
  '2018',
  'enrollment',
  'clouded',
  'by',
  'uncertainty',
  'under',
  'trump'],
 ['conservative',
  'columnist',
  'george',
  'will',
  'the',
  'gop',
  'is',
  'the',
  'party',
  'of',
  'white',
  'people',
  'video'],
 ['woohoo',
  'vets',
  'get',
  'rights',
  'back',
  'obama',
  's',
  'overboard',
  'gun',
  'regulations',
  'for',
  'vets',
  'rolled',
  'back'],
 ['goldman',
  'sachs',
  'chairman',
  'thinks',
  'uk',
  'needs',
  'more',
  'migrants',
  'to',
  'avoid',
  'appearance',
  'of',
  'racism',
  'while',
  'shocking',
  'new',
  'video',
  'tells',
  'another',
  'story'],
 ['america', 's', 'hottest', 'conservative', 'joins', 'fox', 'news', 'team'],
 ['the',
  'world',
  'should',
  'be',
  'outraged',
  'by',
  'sweden',
  's',
  'reward',
  'system',
  'for',
  'returning',
  'jihadists'],
 ['sex',
  'objects',
  'for',
  'hillary',
  'jennifer',
  'lopez',
  'shakes',
  'a',
  's',
  'on',
  'stage',
  'in',
  'thong',
  'for',
  'crooked',
  'hillary',
  'you',
  'can',
  't',
  'make',
  'this',
  'stuff',
  'up',
  'video'],
 ['kremlin',
  'declines',
  'to',
  'comment',
  'on',
  'probe',
  'of',
  'trump',
  'ties',
  'with',
  'russia'],
 ['watch',
  '8th',
  'grader',
  'destroy',
  'disgraced',
  'detroit',
  'city',
  'council',
  'member',
  'and',
  'wife',
  'of',
  'us',
  'representative',
  'in',
  'debate',
  'video'],
 ['keith',
  'olbermann',
  'to',
  'betsy',
  'devos',
  'the',
  'hurricane',
  'is',
  'going',
  'to',
  'do',
  'less',
  'damage',
  'to',
  'schools',
  'than',
  'you',
  'are'],
 ['take',
  'this',
  'short',
  'quiz',
  'which',
  'radical',
  'said',
  'it',
  'we',
  'guarantee',
  'the',
  'answers',
  'will',
  'surprise',
  'you'],
 ['box',
  'office',
  'bomb',
  'seth',
  'rogan',
  'tweeted',
  'f',
  'ck',
  'you',
  'to',
  'ben',
  'carson',
  'america',
  'responds',
  'by',
  'boycotting',
  'his',
  'steve',
  'jobs',
  'movie'],
 ['democrat',
  'cites',
  'drafting',
  'error',
  'in',
  'proposed',
  'capital',
  'rule',
  'amendment'],
 ['czech',
  'president',
  'plans',
  'to',
  'appoint',
  'babis',
  's',
  'cabinet',
  'by',
  'mid',
  'december'],
 ['college',
  'students',
  'admit',
  'they',
  'got',
  'extra',
  'credit',
  'for',
  'attending',
  'hillary',
  'rallies'],
 ['democrats', 'sue', 'republicans', 'over', 'plot', 'to', 'rig', 'election'],
 ['trump',
  'praises',
  'putin',
  'while',
  'tweeting',
  'about',
  'a',
  'nuclear',
  'arms',
  'race'],
 ['senators',
  'say',
  'republican',
  'consensus',
  'is',
  'no',
  'vote',
  'on',
  'obama',
  'court',
  'nominee'],
 ['heartless',
  'democrats',
  'invite',
  'illegals',
  'to',
  'taunt',
  'trump',
  'during',
  'policy',
  'speech',
  'while',
  'trump',
  's',
  'guests'],
 ['watch',
  'hillary',
  'lie',
  'about',
  'libya',
  'to',
  'supporters',
  'we',
  'didn',
  't',
  'lose',
  'a',
  'single',
  'person'],
 ['responsible',
  'gun',
  'owner',
  'who',
  'had',
  'never',
  'fired',
  'one',
  'gets',
  'concealed',
  'permit',
  'in',
  'a',
  'single',
  'day'],
 ['chilling',
  'fox',
  'reporter',
  'james',
  'rosen',
  'recounts',
  'being',
  'spied',
  'on',
  'by',
  'the',
  'obama',
  'mafia',
  'video'],
 ['fox',
  'host',
  'don',
  't',
  'ban',
  'assault',
  'weapons',
  'because',
  'terrorists',
  'would',
  'just',
  'use',
  'crock',
  'pots',
  'video'],
 ['five',
  'facts',
  'about',
  'benghazi',
  'that',
  'hillary',
  'doesn',
  't',
  'want',
  'you',
  'to',
  'know'],
 ['hillary', 's', 'response', 'to', 'trump', 's', 'late', 'night'],
 ['copycat', 'dems', 'fundraise', 'off', 'of', 'trump', 'lookalike', 'hat'],
 ['fmr',
  'dni',
  'james',
  'clapper',
  'trump',
  's',
  'russia',
  'scandal',
  'is',
  'worse',
  'than',
  'watergate',
  'video'],
 ['u',
  's',
  'senators',
  'to',
  'introduce',
  'bill',
  'to',
  'secure',
  'internet',
  'of',
  'things'],
 ['report', 'anti', 'trump'],
 ['clinton',
  'extends',
  'olive',
  'branch',
  'to',
  'sanders',
  'we',
  'will',
  'work',
  'together',
  'on',
  'party',
  'platform'],
 ['oops',
  'list',
  'of',
  'top',
  '10',
  'corporate',
  'tax',
  'dodgers',
  'are',
  'all',
  'hillary',
  'donors',
  'compliments',
  'of',
  'bernie',
  'sanders'],
 ['trump', 'explodes'],
 ['u',
  's',
  'attorney',
  'general',
  'escalates',
  'pressure',
  'on',
  'sanctuary',
  'cities'],
 ['lol',
  'hillary',
  'gets',
  'ambushed',
  'at',
  'book',
  'signing',
  'where',
  's',
  'the',
  '33000',
  'emails',
  'what',
  'happened',
  'to',
  'seth',
  'rich'],
 ['abe',
  'hopes',
  'to',
  'avoid',
  'landing',
  'in',
  'rough',
  'in',
  'golf',
  'outing',
  'with',
  'trump'],
 ['breaking', 'trump', 'wrecks', 'the', 'dnc', 'video'],
 ['russian',
  'roulette',
  'for',
  'law',
  'enforcement',
  'border',
  'patrol',
  'agents',
  'given',
  'awards',
  'for',
  'putting',
  'lives',
  'of',
  'armed',
  'illegal',
  'aliens',
  'before',
  'their',
  'own'],
 ['sarah',
  'palin',
  'silent',
  'as',
  'texas',
  'republicans',
  'strip',
  'medicaid',
  'funding',
  'from',
  'children',
  'with',
  'disabilities'],
 ['ex',
  'catalan',
  'leader',
  'puigdemont',
  'freed',
  'with',
  'conditions',
  'in',
  'belgium'],
 ['trump',
  'says',
  'he',
  'is',
  'close',
  'to',
  'picking',
  'new',
  'fbi',
  'director',
  'lieberman',
  'among',
  'top',
  'candidates'],
 ['obama',
  'plan',
  'to',
  'stop',
  'tax',
  'inversions',
  'stirs',
  'u',
  's',
  'business',
  'concerns'],
 ['egypt',
  's',
  'sisi',
  'discusses',
  'repercussions',
  'of',
  'u',
  's',
  'embassy',
  'decision',
  'with',
  'palestinian',
  'president',
  'abbas',
  'presidency',
  'statement'],
 ['former',
  'joe',
  'biden',
  'secret',
  'service',
  'agent',
  'claims',
  'they',
  'had',
  'to',
  'protect',
  'women',
  'from',
  'him',
  'biden',
  'would',
  'grope',
  'all',
  'of',
  'our',
  'wives',
  'and',
  'girlfriend',
  's',
  'a',
  'es'],
 ['watch',
  'the',
  'nra',
  's',
  'wayne',
  'lapierre',
  'support',
  'then',
  'oppose',
  'then',
  'support',
  'firearm',
  'background',
  'checks',
  'video'],
 ['a',
  'must',
  'watch',
  'video',
  'brilliant',
  'take',
  'on',
  'how',
  'hillary',
  'clinton',
  's',
  'lawlessness',
  'gets',
  'ignored'],
 ['the',
  'george',
  'costanza',
  'of',
  'cnn',
  'destroyed',
  'on',
  'his',
  'own',
  'show',
  'we',
  'have',
  'a',
  'one',
  'party',
  'system'],
 ['just',
  'exposed',
  'clinton',
  'broke',
  'ethics',
  'agreement',
  'with',
  'latest',
  'bombshell',
  'gift',
  'from',
  'this',
  'middle',
  'eastern',
  'country',
  'while',
  'secretary',
  'of',
  'state'],
 ['trump', 'lawyers', 'aim', 'to', 'delay', 'fraud', 'trial', 'at', 'hearing'],
 ['trump',
  'talks',
  'to',
  'u',
  's',
  'automakers',
  'pushes',
  'for',
  'new',
  'american',
  'plants'],
 ['bill',
  'maher',
  'scorches',
  'republicans',
  'stop',
  'blaming',
  'liberals',
  'trump',
  'is',
  'your',
  'problem',
  'video'],
 ['trump',
  'cerberus',
  'ceo',
  'offered',
  'services',
  'hopes',
  'he',
  'not',
  'needed',
  'for',
  'intel',
  'review'],
 ['russia',
  'says',
  'u',
  's',
  'providing',
  'cover',
  'for',
  'islamic',
  'state',
  'in',

In [23]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/martakarnaschodkiewicz/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [24]:
# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()
X_train = [[lemmatizer.lemmatize(word) for word in i] for i in X_train]
X_train
X_test = [[lemmatizer.lemmatize(word) for word in i] for i in X_test]
X_test

[['release', 'of', 'house', 'tax', 'bill', 'delayed', 'until', 'thursday'],
 ['confusion',
  'over',
  'trump',
  's',
  'first',
  'talk',
  'with',
  'foreign',
  'leader'],
 ['obama',
  'say',
  'chinese',
  'led',
  'trade',
  'deal',
  'show',
  'need',
  'for',
  'tpp',
  'washington',
  'post'],
 ['former', 'pastor', 'turned', 'teacher', 'beat', 'student'],
 ['breaking',
  'south',
  'carolina',
  'senate',
  'cave',
  'vote',
  'to',
  'remove',
  'confederate',
  'flag',
  'from',
  'statehouse',
  'ground',
  'because',
  'it',
  's',
  'all',
  'about',
  'the',
  'flag'],
 ['austria',
  's',
  'far',
  'right',
  'freedom',
  'party',
  'congratulates',
  'trump'],
 ['canada',
  'mexico',
  'vow',
  'to',
  'stick',
  'with',
  'nafta',
  'talk',
  'mexico',
  'work',
  'on',
  'plan',
  'b'],
 ['bill',
  'maher',
  'hilariously',
  'torch',
  'whiny',
  'trump',
  's',
  'debate',
  'meltdown'],
 ['italy',
  's',
  'populist',
  '5',
  'star',
  'strengthens',
  'lead',
  'after',
  'sicily',
  'vote',
  'poll'],
 ['wa',
  'murdered',
  '27',
  'year',
  'old',
  'democrat',
  'operative',
  'about',
  'to',
  'blow',
  'the',
  'whistle',
  'on',
  'voter',
  'fraud',
  'when',
  'he',
  'wa',
  'shot',
  'in',
  'the',
  'back',
  'video'],
 ['teen',
  'get',
  'creeped',
  'out',
  'when',
  'republican',
  'lawmaker',
  'asks',
  'if',
  'they',
  'are',
  'virgin',
  'during',
  'statehouse',
  'visit'],
 ['in', 'your', 'face', 'following', 'obama', 's', 'gun', 'control', 'rally'],
 ['obama', 'tell', 'gop', 'to', 'f', 'ck', 'off'],
 ['watch',
  'how',
  'moderate',
  'american',
  'muslim',
  'respond',
  'when',
  'asked',
  'if',
  'they',
  'prefer',
  'u',
  'or',
  'sharia',
  'law'],
 ['trump',
  'retweets',
  'hilarious',
  'video',
  'of',
  'him',
  'hitting',
  'golf',
  'ball',
  'that',
  'hit',
  'crooked',
  'hillary',
  'in',
  'the',
  'head',
  'left',
  'go',
  'nut'],
 ['may',
  'will',
  'allow',
  'brexit',
  'delay',
  'in',
  'exceptional',
  'circumstance'],
 ['clinton',
  'to',
  'accuse',
  'trump',
  'of',
  'embracing',
  'nativist',
  'political',
  'movement'],
 ['trump',
  'freaking',
  'out',
  'over',
  'the',
  'port',
  'a',
  'potty',
  'at',
  'inauguration',
  'for',
  'the',
  'dumbest',
  'reason',
  'image'],
 ['tucker',
  'on',
  'comey',
  's',
  'firing',
  'dictatorship',
  'by',
  'the',
  'unelected',
  'that',
  's',
  'the',
  'real',
  'danger',
  'video'],
 ['about',
  'time',
  'christian',
  'group',
  'sue',
  'amazon',
  'and',
  'splc',
  'for',
  'designation',
  'a',
  'hate',
  'group'],
 ['why',
  '93',
  'yr',
  'old',
  'woman',
  'voted',
  'for',
  'the',
  'first',
  'time',
  'in',
  'her',
  'life',
  'for',
  'trump'],
 ['federal',
  'court',
  'strike',
  'down',
  'racist',
  'texas',
  'voter',
  'id',
  'law'],
 ['ellen',
  'degeneres',
  'refuse',
  'to',
  'have',
  'donald',
  'trump',
  'on',
  'her',
  'show',
  'here',
  's',
  'why',
  'video'],
 ['trump',
  'hire',
  'son',
  's',
  'wedding',
  'planner',
  'to',
  'run',
  'new',
  'york',
  'housing',
  'department'],
 ['at',
  'least',
  '800',
  'civilian',
  'killed',
  'by',
  'coalition',
  'strike',
  'in',
  'iraq',
  'syria',
  'report'],
 ['china',
  'say',
  'confident',
  'in',
  'economic',
  'relation',
  'with',
  'u',
  's',
  'ahead',
  'of',
  'trump',
  'visit'],
 ['jesse',
  'watters',
  'like',
  'you',
  've',
  'never',
  'seen',
  'him',
  'before',
  'watch',
  'him',
  'rip',
  'into',
  'juan',
  'williams',
  'over',
  'calling',
  'trump',
  'family',
  'unpatriotic',
  'school',
  'him',
  'on',
  'corrupt',
  'democratic',
  'party',
  'tie',
  'to',
  'communism'],
 ['barracuda',
  'former',
  'obama',
  'advisor',
  'rant',
  'against',
  'trump',
  'for',
  'keeping',
  'campaign',
  'promise',
  'video'],
 ['vast',
  'majority',
  'of',
  'suspect',
  'in',
  'graft',
  'probe',
  'agreeing',
  'to',
  'settle',
  'crown',
  'prince',
  'say'],
 ['trump',
  's',
  'trying',
  'to',
  'attend',
  'muhammad',
  'ali',
  's',
  'muslim',
  'funeral',
  'his',
  'family',
  's',
  'response',
  'is',
  'brilliant'],
 ['wikileaks',
  'smoking',
  'gun',
  'here',
  's',
  'best',
  'proof',
  'hillary',
  'is',
  'just',
  'a',
  'puppet',
  'for',
  'globalist',
  'george',
  'soros'],
 ['warren',
  'kaine',
  'castro',
  'on',
  'clinton',
  'running',
  'mate',
  'short',
  'list',
  'ap'],
 ['aide',
  'try',
  'to',
  'refocus',
  'u',
  's',
  'tax',
  'debate',
  'after',
  'trump',
  's',
  'corporate',
  'rate',
  'remark'],
 ['karma',
  'birthday',
  'boy',
  'bill',
  'clinton',
  'heckled',
  'by',
  'kid',
  'on',
  'the',
  'golf',
  'course'],
 ['facing', 'tough', 're', 'election'],
 ['right',
  'wing',
  'extremist',
  'try',
  'to',
  'repeat',
  'oklahoma',
  'city',
  'bombing',
  'a',
  'nazi',
  'terrorize',
  'charlottesville'],
 ['saudi',
  'arabia',
  'should',
  'not',
  'forfeit',
  'sovereign',
  'right',
  'to',
  'enrich',
  'uranium',
  'senior',
  'prince'],
 ['fight',
  'erupt',
  'at',
  'pro',
  'trump',
  'rally',
  'on',
  'california',
  'beach'],
 ['saudi',
  'businessman',
  'in',
  'debt',
  'dispute',
  'released',
  'from',
  'detention',
  'source'],
 ['house',
  'leader',
  'say',
  'willing',
  'to',
  'do',
  'conference',
  'committee',
  'on',
  'healthcare'],
 ['puerto',
  'rico',
  'governor',
  'hope',
  'for',
  'open',
  'dialogue',
  'with',
  'mnuchin'],
 ['out',
  'for',
  'vote',
  'battle',
  'over',
  'right',
  'inspires',
  'more',
  'u',
  's',
  'transgender',
  'candidate'],
 ['laura',
  'ingraham',
  's',
  'brilliant',
  'idea',
  'on',
  'how',
  'to',
  'shake',
  'up',
  'liberal',
  'college',
  'campus',
  'video'],
 ['in',
  'virginia',
  'clinton',
  'test',
  'senator',
  'tim',
  'kaine',
  'a',
  'a',
  'safe',
  'vp',
  'pick'],
 ['democrat',
  'across',
  'the',
  'country',
  'are',
  'figuring',
  'out',
  'way',
  'to',
  'force',
  'trump',
  'to',
  'release',
  'his',
  'tax',
  'return'],
 ['fox',
  'anchor',
  'chris',
  'wallace',
  'rip',
  'nra',
  'stooge',
  'a',
  'new',
  'one',
  'for',
  'lying',
  'about',
  'gun',
  'control'],
 ['updated',
  'video',
  'is',
  'this',
  'america',
  'conservative',
  'and',
  'their',
  'family',
  'experience',
  'shocking',
  'abuse',
  'and',
  'shaming',
  'in',
  'their',
  'home',
  'ordered',
  'by',
  'leftist',
  'da',
  'a',
  'part',
  'of',
  'insane',
  'vendetta'],
 ['epic',
  'flashback',
  'megyn',
  'kelly',
  'destroyed',
  'by',
  'newt',
  'gingrich',
  'her',
  'prediction',
  'are',
  '100',
  'wrong',
  'video'],
 ['trump',
  'to',
  'make',
  'announcement',
  'on',
  'any',
  'comey',
  'tape',
  'this',
  'week',
  'white',
  'house'],
 ['insane',
  'secret',
  'deal',
  'obama',
  'made',
  'with',
  'death',
  'to',
  'america',
  's',
  'iran',
  'includes',
  'iran',
  'monitoring',
  'their',
  'own',
  'nuclear',
  'site'],
 ['exxon',
  'probe',
  'is',
  'unconstitutional',
  'republican',
  'prosecutor',
  'say'],
 ['china',
  'complains',
  'to',
  'australia',
  'over',
  'turnbull',
  'comment',
  'on',
  'interference'],
 ['dear', 'liberal'],
 ['epipen',
  'ceo',
  'under',
  'fire',
  'for',
  'price',
  'gouging',
  'is',
  'daughter',
  'of',
  'u',
  'senator'],
 ['samantha',
  'bee',
  'take',
  'on',
  'the',
  'nra',
  'and',
  'it',
  'asinine',
  'mascot',
  'and',
  'it',
  'is',
  'glorious',
  'video'],
 ['obama',
  'to',
  'u',
  's',
  'military',
  'on',
  'putin',
  'he',
  'did',
  'not',
  'take',
  'my',
  'warning',
  'on',
  'syria',
  'encourages',
  'russian',
  'to',
  'get',
  'a',
  'little',
  'smarter'],
 ['united',
  'nation',
  'chief',
  'very',
  'worried',
  'by',
  'saudi',
  'lebanon',
  'tension'],
 ['kellyanne',
  'conway',
  'trump',
  'is',
  'gracious',
  'to',
  'not',
  'prosecute',
  'clinton',
  'while',
  'recount',
  'is',
  'underway',
  'video'],
 ['trump',
  'on',
  'twitter',
  'august',
  '8',
  'opioid',
  'crisis',
  'north',
  'korea'],
 ['u',
  's',
  'diplomat',
  'warns',
  'against',
  'isolationism',
  'in',
  'implicit',
  'trump',
  'rebuke'],
 ['right',
  'wing',
  'boogeyman',
  'george',
  'soros',
  'pop',
  'out',
  'to',
  'scare',
  'conservative',
  'by',
  'calling',
  'out',
  'trump'],
 ['liberal',
  'freak',
  'out',
  'trump',
  'wipe',
  'out',
  'one',
  'of',
  'obama',
  's',
  'most',
  'controversial',
  'executive',
  'action',
  'give',
  'right',
  'back',
  'to',
  'state',
  'video'],
 ['trump',
  's',
  'lawyer',
  'say',
  'trump',
  'ha',
  'no',
  'russian',
  'income',
  'with',
  'a',
  'few',
  'exception'],
 ['moscow',
  'ha',
  'never',
  'supported',
  'complete',
  'embargo',
  'on',
  'north',
  'korea',
  'ria',
  'cite',
  'deputy',
  'fm'],
 ['vp',
  'joe',
  'biden',
  'to',
  'make',
  'appearance',
  'at',
  'oscar',
  'to',
  'introduce',
  'song',
  'about',
  'sexual',
  'assault'],
 ['exclusive',
  'trump',
  'say',
  'republican',
  'border',
  'tax',
  'could',
  'boost',
  'u',
  's',
  'job'],
 ['lol',
  'un',
  'refugee',
  'spoke',
  'celebrity',
  'angelina',
  'jolie',
  'admonishes',
  'u',
  's',
  'for',
  'undermining',
  'international',
  'law',
  'by',
  'resisting',
  'flow',
  'of',
  'muslim',
  'refugee'],
 ['chad', 'reject', 'u', 's', 'bribery', 'allegation', 'against', 'president'],
 ['rip',
  'proud',
  'patriot',
  'marine',
  'dy',
  'after',
  'delivering',
  'powerful',
  'message',
  'to',
  'president',
  'trump'],
 ['chris',
  'wallace',
  'just',
  'shoved',
  'his',
  'foot',
  'so',
  'far',
  'up',
  'trump',
  's',
  'as',
  'it',
  'came',
  'out',
  'his',
  'mouth',
  'video'],
 ['bernie',
  'sander',
  'open',
  'to',
  'being',
  'clinton',
  's',
  'v',
  'p',
  'video'],
 ['facebook',
  'twitter',
  'support',
  'apple',
  'on',
  'encryption',
  'dispute',
  'with',
  'fbi'],
 ['poverty',
  'pimp',
  'al',
  'sharpton',
  'us',
  'the',
  'bible',
  'to',
  'say',
  'dems',
  'should',
  'give',
  'the',
  'big',
  'payback',
  'to',
  'republican'],
 ['kellyanne',
  'conway',
  'on',
  'trump',
  's',
  'terrorism',
  'policy',
  'we',
  'need',
  'more',
  'careful',
  'and',
  'extreme',
  'vetting',
  'video'],
 ['video',
  'american',
  'vet',
  'dy',
  'fighting',
  'isi',
  'couldn',
  't',
  'sit',
  'back',
  'and',
  'watch',
  'iraq',
  'being',
  'taken',
  'over',
  'by',
  'isi',
  'after',
  'his',
  'brother',
  'shed',
  'their',
  'blood',
  'to',
  'make',
  'iraq',
  'free',
  'democracy'],
 ['oas',
  'say',
  'honduran',
  'vote',
  'result',
  'in',
  'doubt',
  'due',
  'to',
  'irregularity'],
 ['donald',
  'trump',
  's',
  'touching',
  'gesture',
  'after',
  'rally',
  'caught',
  'on',
  'video'],
 ['is',
  'a',
  'gop',
  'civil',
  'war',
  'coming',
  'rnc',
  'chair',
  'accidentally',
  'spoke',
  'the',
  'truth',
  'about',
  '2016',
  'nomination',
  'process'],
 ['unreal',
  'pro',
  'cuba',
  'travel',
  'at',
  'pb',
  'and',
  'nbc',
  'cuba',
  'ha',
  'so',
  'much',
  'going',
  'for',
  'it',
  'it',
  's',
  'proudly',
  'communist',
  'video'],
 ['britain',
  's',
  'may',
  'party',
  'leader',
  'agree',
  'to',
  'tackle',
  'sexual',
  'harassment',
  'with',
  'new',
  'measure'],
 ['senator', 'wyden', 'pledge', 'to', 'fight', 'limit', 'on', 'encryption'],
 ['alabama',
  'attorney',
  'general',
  'named',
  'to',
  'jeff',
  'session',
  'senate',
  'seat'],
 ['family',
  'returning',
  'to',
  'ruined',
  'philippine',
  'city',
  'taught',
  'to',
  'identify',
  'bomb'],
 ['desperate',
  'lindsey',
  'graham',
  'call',
  'clinton',
  'foundation',
  'controversy',
  'a',
  'gift',
  'from',
  'the',
  'political',
  'god',
  'video'],
 ['trump', 'take', 'credit', 'for', 'republican', 'win', 'in', 'georgia'],
 ['powerful',
  'moment',
  'between',
  'biden',
  'and',
  'protester',
  'end',
  'up',
  'with',
  'invitation',
  'backstage',
  'video'],
 ['black',
  'leader',
  'call',
  'on',
  'black',
  'caucus',
  'member',
  'to',
  'resign',
  'praise',
  'trump',
  's',
  'visit',
  'to',
  'detroit',
  'video'],
 ['million',
  'of',
  'insecure',
  'gadget',
  'exposed',
  'in',
  'european',
  'city',
  'report'],
 ['democrat',
  'literally',
  'scream',
  'shame',
  'at',
  'republican',
  'for',
  'blocking',
  'lgbt',
  'amendment',
  'video'],
 ['house', 'seek', 'to', 'tighten', 'restriction', 'on', 'pakistan', 'aid'],
 ['obamacare',
  '2018',
  'enrollment',
  'clouded',
  'by',
  'uncertainty',
  'under',
  'trump'],
 ['conservative',
  'columnist',
  'george',
  'will',
  'the',
  'gop',
  'is',
  'the',
  'party',
  'of',
  'white',
  'people',
  'video'],
 ['woohoo',
  'vet',
  'get',
  'right',
  'back',
  'obama',
  's',
  'overboard',
  'gun',
  'regulation',
  'for',
  'vet',
  'rolled',
  'back'],
 ['goldman',
  'sachs',
  'chairman',
  'think',
  'uk',
  'need',
  'more',
  'migrant',
  'to',
  'avoid',
  'appearance',
  'of',
  'racism',
  'while',
  'shocking',
  'new',
  'video',
  'tell',
  'another',
  'story'],
 ['america', 's', 'hottest', 'conservative', 'join', 'fox', 'news', 'team'],
 ['the',
  'world',
  'should',
  'be',
  'outraged',
  'by',
  'sweden',
  's',
  'reward',
  'system',
  'for',
  'returning',
  'jihadist'],
 ['sex',
  'object',
  'for',
  'hillary',
  'jennifer',
  'lopez',
  'shake',
  'a',
  's',
  'on',
  'stage',
  'in',
  'thong',
  'for',
  'crooked',
  'hillary',
  'you',
  'can',
  't',
  'make',
  'this',
  'stuff',
  'up',
  'video'],
 ['kremlin',
  'decline',
  'to',
  'comment',
  'on',
  'probe',
  'of',
  'trump',
  'tie',
  'with',
  'russia'],
 ['watch',
  '8th',
  'grader',
  'destroy',
  'disgraced',
  'detroit',
  'city',
  'council',
  'member',
  'and',
  'wife',
  'of',
  'u',
  'representative',
  'in',
  'debate',
  'video'],
 ['keith',
  'olbermann',
  'to',
  'betsy',
  'devos',
  'the',
  'hurricane',
  'is',
  'going',
  'to',
  'do',
  'less',
  'damage',
  'to',
  'school',
  'than',
  'you',
  'are'],
 ['take',
  'this',
  'short',
  'quiz',
  'which',
  'radical',
  'said',
  'it',
  'we',
  'guarantee',
  'the',
  'answer',
  'will',
  'surprise',
  'you'],
 ['box',
  'office',
  'bomb',
  'seth',
  'rogan',
  'tweeted',
  'f',
  'ck',
  'you',
  'to',
  'ben',
  'carson',
  'america',
  'responds',
  'by',
  'boycotting',
  'his',
  'steve',
  'job',
  'movie'],
 ['democrat',
  'cite',
  'drafting',
  'error',
  'in',
  'proposed',
  'capital',
  'rule',
  'amendment'],
 ['czech',
  'president',
  'plan',
  'to',
  'appoint',
  'babis',
  's',
  'cabinet',
  'by',
  'mid',
  'december'],
 ['college',
  'student',
  'admit',
  'they',
  'got',
  'extra',
  'credit',
  'for',
  'attending',
  'hillary',
  'rally'],
 ['democrat', 'sue', 'republican', 'over', 'plot', 'to', 'rig', 'election'],
 ['trump',
  'praise',
  'putin',
  'while',
  'tweeting',
  'about',
  'a',
  'nuclear',
  'arm',
  'race'],
 ['senator',
  'say',
  'republican',
  'consensus',
  'is',
  'no',
  'vote',
  'on',
  'obama',
  'court',
  'nominee'],
 ['heartless',
  'democrat',
  'invite',
  'illegals',
  'to',
  'taunt',
  'trump',
  'during',
  'policy',
  'speech',
  'while',
  'trump',
  's',
  'guest'],
 ['watch',
  'hillary',
  'lie',
  'about',
  'libya',
  'to',
  'supporter',
  'we',
  'didn',
  't',
  'lose',
  'a',
  'single',
  'person'],
 ['responsible',
  'gun',
  'owner',
  'who',
  'had',
  'never',
  'fired',
  'one',
  'get',
  'concealed',
  'permit',
  'in',
  'a',
  'single',
  'day'],
 ['chilling',
  'fox',
  'reporter',
  'james',
  'rosen',
  'recount',
  'being',
  'spied',
  'on',
  'by',
  'the',
  'obama',
  'mafia',
  'video'],
 ['fox',
  'host',
  'don',
  't',
  'ban',
  'assault',
  'weapon',
  'because',
  'terrorist',
  'would',
  'just',
  'use',
  'crock',
  'pot',
  'video'],
 ['five',
  'fact',
  'about',
  'benghazi',
  'that',
  'hillary',
  'doesn',
  't',
  'want',
  'you',
  'to',
  'know'],
 ['hillary', 's', 'response', 'to', 'trump', 's', 'late', 'night'],
 ['copycat', 'dems', 'fundraise', 'off', 'of', 'trump', 'lookalike', 'hat'],
 ['fmr',
  'dni',
  'james',
  'clapper',
  'trump',
  's',
  'russia',
  'scandal',
  'is',
  'worse',
  'than',
  'watergate',
  'video'],
 ['u',
  's',
  'senator',
  'to',
  'introduce',
  'bill',
  'to',
  'secure',
  'internet',
  'of',
  'thing'],
 ['report', 'anti', 'trump'],
 ['clinton',
  'extends',
  'olive',
  'branch',
  'to',
  'sander',
  'we',
  'will',
  'work',
  'together',
  'on',
  'party',
  'platform'],
 ['oops',
  'list',
  'of',
  'top',
  '10',
  'corporate',
  'tax',
  'dodger',
  'are',
  'all',
  'hillary',
  'donor',
  'compliment',
  'of',
  'bernie',
  'sander'],
 ['trump', 'explodes'],
 ['u',
  's',
  'attorney',
  'general',
  'escalates',
  'pressure',
  'on',
  'sanctuary',
  'city'],
 ['lol',
  'hillary',
  'get',
  'ambushed',
  'at',
  'book',
  'signing',
  'where',
  's',
  'the',
  '33000',
  'email',
  'what',
  'happened',
  'to',
  'seth',
  'rich'],
 ['abe',
  'hope',
  'to',
  'avoid',
  'landing',
  'in',
  'rough',
  'in',
  'golf',
  'outing',
  'with',
  'trump'],
 ['breaking', 'trump', 'wreck', 'the', 'dnc', 'video'],
 ['russian',
  'roulette',
  'for',
  'law',
  'enforcement',
  'border',
  'patrol',
  'agent',
  'given',
  'award',
  'for',
  'putting',
  'life',
  'of',
  'armed',
  'illegal',
  'alien',
  'before',
  'their',
  'own'],
 ['sarah',
  'palin',
  'silent',
  'a',
  'texas',
  'republican',
  'strip',
  'medicaid',
  'funding',
  'from',
  'child',
  'with',
  'disability'],
 ['ex',
  'catalan',
  'leader',
  'puigdemont',
  'freed',
  'with',
  'condition',
  'in',
  'belgium'],
 ['trump',
  'say',
  'he',
  'is',
  'close',
  'to',
  'picking',
  'new',
  'fbi',
  'director',
  'lieberman',
  'among',
  'top',
  'candidate'],
 ['obama',
  'plan',
  'to',
  'stop',
  'tax',
  'inversion',
  'stir',
  'u',
  's',
  'business',
  'concern'],
 ['egypt',
  's',
  'sisi',
  'discusses',
  'repercussion',
  'of',
  'u',
  's',
  'embassy',
  'decision',
  'with',
  'palestinian',
  'president',
  'abbas',
  'presidency',
  'statement'],
 ['former',
  'joe',
  'biden',
  'secret',
  'service',
  'agent',
  'claim',
  'they',
  'had',
  'to',
  'protect',
  'woman',
  'from',
  'him',
  'biden',
  'would',
  'grope',
  'all',
  'of',
  'our',
  'wife',
  'and',
  'girlfriend',
  's',
  'a',
  'e'],
 ['watch',
  'the',
  'nra',
  's',
  'wayne',
  'lapierre',
  'support',
  'then',
  'oppose',
  'then',
  'support',
  'firearm',
  'background',
  'check',
  'video'],
 ['a',
  'must',
  'watch',
  'video',
  'brilliant',
  'take',
  'on',
  'how',
  'hillary',
  'clinton',
  's',
  'lawlessness',
  'get',
  'ignored'],
 ['the',
  'george',
  'costanza',
  'of',
  'cnn',
  'destroyed',
  'on',
  'his',
  'own',
  'show',
  'we',
  'have',
  'a',
  'one',
  'party',
  'system'],
 ['just',
  'exposed',
  'clinton',
  'broke',
  'ethic',
  'agreement',
  'with',
  'latest',
  'bombshell',
  'gift',
  'from',
  'this',
  'middle',
  'eastern',
  'country',
  'while',
  'secretary',
  'of',
  'state'],
 ['trump', 'lawyer', 'aim', 'to', 'delay', 'fraud', 'trial', 'at', 'hearing'],
 ['trump',
  'talk',
  'to',
  'u',
  's',
  'automaker',
  'push',
  'for',
  'new',
  'american',
  'plant'],
 ['bill',
  'maher',
  'scorch',
  'republican',
  'stop',
  'blaming',
  'liberal',
  'trump',
  'is',
  'your',
  'problem',
  'video'],
 ['trump',
  'cerberus',
  'ceo',
  'offered',
  'service',
  'hope',
  'he',
  'not',
  'needed',
  'for',
  'intel',
  'review'],
 ['russia',
  'say',
  'u',
  's',
  'providing',
  'cover',
  'for',
  'islamic',
  'state',
  'in',
  'syria'],
 ['u',
  's',
  'weakens',
  'retirement',
  'advice',
  'rule',
  'responding',
  'to',
  'industry'],
 ['grief',
  'stricken',
  'family',
  'of',
  'japanese',
  'abducted',
  'by',
  'north',
  'korea',
  'pin',
  'hope',

In [25]:
# Initialize the stop words
stop_words = set(stopwords.words('english'))
X_train = [[word for word in i if word not in stop_words] for i in X_train]
X_train
X_test = [[word for word in i if word not in stop_words] for i in X_test]
X_test

[['release', 'house', 'tax', 'bill', 'delayed', 'thursday'],
 ['confusion', 'trump', 'first', 'talk', 'foreign', 'leader'],
 ['obama',
  'say',
  'chinese',
  'led',
  'trade',
  'deal',
  'show',
  'need',
  'tpp',
  'washington',
  'post'],
 ['former', 'pastor', 'turned', 'teacher', 'beat', 'student'],
 ['breaking',
  'south',
  'carolina',
  'senate',
  'cave',
  'vote',
  'remove',
  'confederate',
  'flag',
  'statehouse',
  'ground',
  'flag'],
 ['austria', 'far', 'right', 'freedom', 'party', 'congratulates', 'trump'],
 ['canada',
  'mexico',
  'vow',
  'stick',
  'nafta',
  'talk',
  'mexico',
  'work',
  'plan',
  'b'],
 ['bill',
  'maher',
  'hilariously',
  'torch',
  'whiny',
  'trump',
  'debate',
  'meltdown'],
 ['italy',
  'populist',
  '5',
  'star',
  'strengthens',
  'lead',
  'sicily',
  'vote',
  'poll'],
 ['wa',
  'murdered',
  '27',
  'year',
  'old',
  'democrat',
  'operative',
  'blow',
  'whistle',
  'voter',
  'fraud',
  'wa',
  'shot',
  'back',
  'video'],
 ['teen',
  'get',
  'creeped',
  'republican',
  'lawmaker',
  'asks',
  'virgin',
  'statehouse',
  'visit'],
 ['face', 'following', 'obama', 'gun', 'control', 'rally'],
 ['obama', 'tell', 'gop', 'f', 'ck'],
 ['watch',
  'moderate',
  'american',
  'muslim',
  'respond',
  'asked',
  'prefer',
  'u',
  'sharia',
  'law'],
 ['trump',
  'retweets',
  'hilarious',
  'video',
  'hitting',
  'golf',
  'ball',
  'hit',
  'crooked',
  'hillary',
  'head',
  'left',
  'go',
  'nut'],
 ['may', 'allow', 'brexit', 'delay', 'exceptional', 'circumstance'],
 ['clinton',
  'accuse',
  'trump',
  'embracing',
  'nativist',
  'political',
  'movement'],
 ['trump',
  'freaking',
  'port',
  'potty',
  'inauguration',
  'dumbest',
  'reason',
  'image'],
 ['tucker',
  'comey',
  'firing',
  'dictatorship',
  'unelected',
  'real',
  'danger',
  'video'],
 ['time',
  'christian',
  'group',
  'sue',
  'amazon',
  'splc',
  'designation',
  'hate',
  'group'],
 ['93', 'yr', 'old', 'woman', 'voted', 'first', 'time', 'life', 'trump'],
 ['federal', 'court', 'strike', 'racist', 'texas', 'voter', 'id', 'law'],
 ['ellen', 'degeneres', 'refuse', 'donald', 'trump', 'show', 'video'],
 ['trump',
  'hire',
  'son',
  'wedding',
  'planner',
  'run',
  'new',
  'york',
  'housing',
  'department'],
 ['least',
  '800',
  'civilian',
  'killed',
  'coalition',
  'strike',
  'iraq',
  'syria',
  'report'],
 ['china',
  'say',
  'confident',
  'economic',
  'relation',
  'u',
  'ahead',
  'trump',
  'visit'],
 ['jesse',
  'watters',
  'like',
  'never',
  'seen',
  'watch',
  'rip',
  'juan',
  'williams',
  'calling',
  'trump',
  'family',
  'unpatriotic',
  'school',
  'corrupt',
  'democratic',
  'party',
  'tie',
  'communism'],
 ['barracuda',
  'former',
  'obama',
  'advisor',
  'rant',
  'trump',
  'keeping',
  'campaign',
  'promise',
  'video'],
 ['vast',
  'majority',
  'suspect',
  'graft',
  'probe',
  'agreeing',
  'settle',
  'crown',
  'prince',
  'say'],
 ['trump',
  'trying',
  'attend',
  'muhammad',
  'ali',
  'muslim',
  'funeral',
  'family',
  'response',
  'brilliant'],
 ['wikileaks',
  'smoking',
  'gun',
  'best',
  'proof',
  'hillary',
  'puppet',
  'globalist',
  'george',
  'soros'],
 ['warren',
  'kaine',
  'castro',
  'clinton',
  'running',
  'mate',
  'short',
  'list',
  'ap'],
 ['aide',
  'try',
  'refocus',
  'u',
  'tax',
  'debate',
  'trump',
  'corporate',
  'rate',
  'remark'],
 ['karma',
  'birthday',
  'boy',
  'bill',
  'clinton',
  'heckled',
  'kid',
  'golf',
  'course'],
 ['facing', 'tough', 'election'],
 ['right',
  'wing',
  'extremist',
  'try',
  'repeat',
  'oklahoma',
  'city',
  'bombing',
  'nazi',
  'terrorize',
  'charlottesville'],
 ['saudi',
  'arabia',
  'forfeit',
  'sovereign',
  'right',
  'enrich',
  'uranium',
  'senior',
  'prince'],
 ['fight', 'erupt', 'pro', 'trump', 'rally', 'california', 'beach'],
 ['saudi',
  'businessman',
  'debt',
  'dispute',
  'released',
  'detention',
  'source'],
 ['house',
  'leader',
  'say',
  'willing',
  'conference',
  'committee',
  'healthcare'],
 ['puerto', 'rico', 'governor', 'hope', 'open', 'dialogue', 'mnuchin'],
 ['vote', 'battle', 'right', 'inspires', 'u', 'transgender', 'candidate'],
 ['laura',
  'ingraham',
  'brilliant',
  'idea',
  'shake',
  'liberal',
  'college',
  'campus',
  'video'],
 ['virginia',
  'clinton',
  'test',
  'senator',
  'tim',
  'kaine',
  'safe',
  'vp',
  'pick'],
 ['democrat',
  'across',
  'country',
  'figuring',
  'way',
  'force',
  'trump',
  'release',
  'tax',
  'return'],
 ['fox',
  'anchor',
  'chris',
  'wallace',
  'rip',
  'nra',
  'stooge',
  'new',
  'one',
  'lying',
  'gun',
  'control'],
 ['updated',
  'video',
  'america',
  'conservative',
  'family',
  'experience',
  'shocking',
  'abuse',
  'shaming',
  'home',
  'ordered',
  'leftist',
  'da',
  'part',
  'insane',
  'vendetta'],
 ['epic',
  'flashback',
  'megyn',
  'kelly',
  'destroyed',
  'newt',
  'gingrich',
  'prediction',
  '100',
  'wrong',
  'video'],
 ['trump', 'make', 'announcement', 'comey', 'tape', 'week', 'white', 'house'],
 ['insane',
  'secret',
  'deal',
  'obama',
  'made',
  'death',
  'america',
  'iran',
  'includes',
  'iran',
  'monitoring',
  'nuclear',
  'site'],
 ['exxon', 'probe', 'unconstitutional', 'republican', 'prosecutor', 'say'],
 ['china', 'complains', 'australia', 'turnbull', 'comment', 'interference'],
 ['dear', 'liberal'],
 ['epipen', 'ceo', 'fire', 'price', 'gouging', 'daughter', 'u', 'senator'],
 ['samantha', 'bee', 'take', 'nra', 'asinine', 'mascot', 'glorious', 'video'],
 ['obama',
  'u',
  'military',
  'putin',
  'take',
  'warning',
  'syria',
  'encourages',
  'russian',
  'get',
  'little',
  'smarter'],
 ['united', 'nation', 'chief', 'worried', 'saudi', 'lebanon', 'tension'],
 ['kellyanne',
  'conway',
  'trump',
  'gracious',
  'prosecute',
  'clinton',
  'recount',
  'underway',
  'video'],
 ['trump', 'twitter', 'august', '8', 'opioid', 'crisis', 'north', 'korea'],
 ['u', 'diplomat', 'warns', 'isolationism', 'implicit', 'trump', 'rebuke'],
 ['right',
  'wing',
  'boogeyman',
  'george',
  'soros',
  'pop',
  'scare',
  'conservative',
  'calling',
  'trump'],
 ['liberal',
  'freak',
  'trump',
  'wipe',
  'one',
  'obama',
  'controversial',
  'executive',
  'action',
  'give',
  'right',
  'back',
  'state',
  'video'],
 ['trump', 'lawyer', 'say', 'trump', 'ha', 'russian', 'income', 'exception'],
 ['moscow',
  'ha',
  'never',
  'supported',
  'complete',
  'embargo',
  'north',
  'korea',
  'ria',
  'cite',
  'deputy',
  'fm'],
 ['vp',
  'joe',
  'biden',
  'make',
  'appearance',
  'oscar',
  'introduce',
  'song',
  'sexual',
  'assault'],
 ['exclusive',
  'trump',
  'say',
  'republican',
  'border',
  'tax',
  'could',
  'boost',
  'u',
  'job'],
 ['lol',
  'un',
  'refugee',
  'spoke',
  'celebrity',
  'angelina',
  'jolie',
  'admonishes',
  'u',
  'undermining',
  'international',
  'law',
  'resisting',
  'flow',
  'muslim',
  'refugee'],
 ['chad', 'reject', 'u', 'bribery', 'allegation', 'president'],
 ['rip',
  'proud',
  'patriot',
  'marine',
  'dy',
  'delivering',
  'powerful',
  'message',
  'president',
  'trump'],
 ['chris',
  'wallace',
  'shoved',
  'foot',
  'far',
  'trump',
  'came',
  'mouth',
  'video'],
 ['bernie', 'sander', 'open', 'clinton', 'v', 'p', 'video'],
 ['facebook', 'twitter', 'support', 'apple', 'encryption', 'dispute', 'fbi'],
 ['poverty',
  'pimp',
  'al',
  'sharpton',
  'us',
  'bible',
  'say',
  'dems',
  'give',
  'big',
  'payback',
  'republican'],
 ['kellyanne',
  'conway',
  'trump',
  'terrorism',
  'policy',
  'need',
  'careful',
  'extreme',
  'vetting',
  'video'],
 ['video',
  'american',
  'vet',
  'dy',
  'fighting',
  'isi',
  'sit',
  'back',
  'watch',
  'iraq',
  'taken',
  'isi',
  'brother',
  'shed',
  'blood',
  'make',
  'iraq',
  'free',
  'democracy'],
 ['oas', 'say', 'honduran', 'vote', 'result', 'doubt', 'due', 'irregularity'],
 ['donald', 'trump', 'touching', 'gesture', 'rally', 'caught', 'video'],
 ['gop',
  'civil',
  'war',
  'coming',
  'rnc',
  'chair',
  'accidentally',
  'spoke',
  'truth',
  '2016',
  'nomination',
  'process'],
 ['unreal',
  'pro',
  'cuba',
  'travel',
  'pb',
  'nbc',
  'cuba',
  'ha',
  'much',
  'going',
  'proudly',
  'communist',
  'video'],
 ['britain',
  'may',
  'party',
  'leader',
  'agree',
  'tackle',
  'sexual',
  'harassment',
  'new',
  'measure'],
 ['senator', 'wyden', 'pledge', 'fight', 'limit', 'encryption'],
 ['alabama',
  'attorney',
  'general',
  'named',
  'jeff',
  'session',
  'senate',
  'seat'],
 ['family',
  'returning',
  'ruined',
  'philippine',
  'city',
  'taught',
  'identify',
  'bomb'],
 ['desperate',
  'lindsey',
  'graham',
  'call',
  'clinton',
  'foundation',
  'controversy',
  'gift',
  'political',
  'god',
  'video'],
 ['trump', 'take', 'credit', 'republican', 'win', 'georgia'],
 ['powerful',
  'moment',
  'biden',
  'protester',
  'end',
  'invitation',
  'backstage',
  'video'],
 ['black',
  'leader',
  'call',
  'black',
  'caucus',
  'member',
  'resign',
  'praise',
  'trump',
  'visit',
  'detroit',
  'video'],
 ['million', 'insecure', 'gadget', 'exposed', 'european', 'city', 'report'],
 ['democrat',
  'literally',
  'scream',
  'shame',
  'republican',
  'blocking',
  'lgbt',
  'amendment',
  'video'],
 ['house', 'seek', 'tighten', 'restriction', 'pakistan', 'aid'],
 ['obamacare', '2018', 'enrollment', 'clouded', 'uncertainty', 'trump'],
 ['conservative',
  'columnist',
  'george',
  'gop',
  'party',
  'white',
  'people',
  'video'],
 ['woohoo',
  'vet',
  'get',
  'right',
  'back',
  'obama',
  'overboard',
  'gun',
  'regulation',
  'vet',
  'rolled',
  'back'],
 ['goldman',
  'sachs',
  'chairman',
  'think',
  'uk',
  'need',
  'migrant',
  'avoid',
  'appearance',
  'racism',
  'shocking',
  'new',
  'video',
  'tell',
  'another',
  'story'],
 ['america', 'hottest', 'conservative', 'join', 'fox', 'news', 'team'],
 ['world', 'outraged', 'sweden', 'reward', 'system', 'returning', 'jihadist'],
 ['sex',
  'object',
  'hillary',
  'jennifer',
  'lopez',
  'shake',
  'stage',
  'thong',
  'crooked',
  'hillary',
  'make',
  'stuff',
  'video'],
 ['kremlin', 'decline', 'comment', 'probe', 'trump', 'tie', 'russia'],
 ['watch',
  '8th',
  'grader',
  'destroy',
  'disgraced',
  'detroit',
  'city',
  'council',
  'member',
  'wife',
  'u',
  'representative',
  'debate',
  'video'],
 ['keith',
  'olbermann',
  'betsy',
  'devos',
  'hurricane',
  'going',
  'less',
  'damage',
  'school'],
 ['take',
  'short',
  'quiz',
  'radical',
  'said',
  'guarantee',
  'answer',
  'surprise'],
 ['box',
  'office',
  'bomb',
  'seth',
  'rogan',
  'tweeted',
  'f',
  'ck',
  'ben',
  'carson',
  'america',
  'responds',
  'boycotting',
  'steve',
  'job',
  'movie'],
 ['democrat',
  'cite',
  'drafting',
  'error',
  'proposed',
  'capital',
  'rule',
  'amendment'],
 ['czech',
  'president',
  'plan',
  'appoint',
  'babis',
  'cabinet',
  'mid',
  'december'],
 ['college',
  'student',
  'admit',
  'got',
  'extra',
  'credit',
  'attending',
  'hillary',
  'rally'],
 ['democrat', 'sue', 'republican', 'plot', 'rig', 'election'],
 ['trump', 'praise', 'putin', 'tweeting', 'nuclear', 'arm', 'race'],
 ['senator',
  'say',
  'republican',
  'consensus',
  'vote',
  'obama',
  'court',
  'nominee'],
 ['heartless',
  'democrat',
  'invite',
  'illegals',
  'taunt',
  'trump',
  'policy',
  'speech',
  'trump',
  'guest'],
 ['watch', 'hillary', 'lie', 'libya', 'supporter', 'lose', 'single', 'person'],
 ['responsible',
  'gun',
  'owner',
  'never',
  'fired',
  'one',
  'get',
  'concealed',
  'permit',
  'single',
  'day'],
 ['chilling',
  'fox',
  'reporter',
  'james',
  'rosen',
  'recount',
  'spied',
  'obama',
  'mafia',
  'video'],
 ['fox',
  'host',
  'ban',
  'assault',
  'weapon',
  'terrorist',
  'would',
  'use',
  'crock',
  'pot',
  'video'],
 ['five', 'fact', 'benghazi', 'hillary', 'want', 'know'],
 ['hillary', 'response', 'trump', 'late', 'night'],
 ['copycat', 'dems', 'fundraise', 'trump', 'lookalike', 'hat'],
 ['fmr',
  'dni',
  'james',
  'clapper',
  'trump',
  'russia',
  'scandal',
  'worse',
  'watergate',
  'video'],
 ['u', 'senator', 'introduce', 'bill', 'secure', 'internet', 'thing'],
 ['report', 'anti', 'trump'],
 ['clinton',
  'extends',
  'olive',
  'branch',
  'sander',
  'work',
  'together',
  'party',
  'platform'],
 ['oops',
  'list',
  'top',
  '10',
  'corporate',
  'tax',
  'dodger',
  'hillary',
  'donor',
  'compliment',
  'bernie',
  'sander'],
 ['trump', 'explodes'],
 ['u', 'attorney', 'general', 'escalates', 'pressure', 'sanctuary', 'city'],
 ['lol',
  'hillary',
  'get',
  'ambushed',
  'book',
  'signing',
  '33000',
  'email',
  'happened',
  'seth',
  'rich'],
 ['abe', 'hope', 'avoid', 'landing', 'rough', 'golf', 'outing', 'trump'],
 ['breaking', 'trump', 'wreck', 'dnc', 'video'],
 ['russian',
  'roulette',
  'law',
  'enforcement',
  'border',
  'patrol',
  'agent',
  'given',
  'award',
  'putting',
  'life',
  'armed',
  'illegal',
  'alien'],
 ['sarah',
  'palin',
  'silent',
  'texas',
  'republican',
  'strip',
  'medicaid',
  'funding',
  'child',
  'disability'],
 ['ex', 'catalan', 'leader', 'puigdemont', 'freed', 'condition', 'belgium'],
 ['trump',
  'say',
  'close',
  'picking',
  'new',
  'fbi',
  'director',
  'lieberman',
  'among',
  'top',
  'candidate'],
 ['obama',
  'plan',
  'stop',
  'tax',
  'inversion',
  'stir',
  'u',
  'business',
  'concern'],
 ['egypt',
  'sisi',
  'discusses',
  'repercussion',
  'u',
  'embassy',
  'decision',
  'palestinian',
  'president',
  'abbas',
  'presidency',
  'statement'],
 ['former',
  'joe',
  'biden',
  'secret',
  'service',
  'agent',
  'claim',
  'protect',
  'woman',
  'biden',
  'would',
  'grope',
  'wife',
  'girlfriend',
  'e'],
 ['watch',
  'nra',
  'wayne',
  'lapierre',
  'support',
  'oppose',
  'support',
  'firearm',
  'background',
  'check',
  'video'],
 ['must',
  'watch',
  'video',
  'brilliant',
  'take',
  'hillary',
  'clinton',
  'lawlessness',
  'get',
  'ignored'],
 ['george', 'costanza', 'cnn', 'destroyed', 'show', 'one', 'party', 'system'],
 ['exposed',
  'clinton',
  'broke',
  'ethic',
  'agreement',
  'latest',
  'bombshell',
  'gift',
  'middle',
  'eastern',
  'country',
  'secretary',
  'state'],
 ['trump', 'lawyer', 'aim', 'delay', 'fraud', 'trial', 'hearing'],
 ['trump', 'talk', 'u', 'automaker', 'push', 'new', 'american', 'plant'],
 ['bill',
  'maher',
  'scorch',
  'republican',
  'stop',
  'blaming',
  'liberal',
  'trump',
  'problem',
  'video'],
 ['trump',
  'cerberus',
  'ceo',
  'offered',
  'service',
  'hope',
  'needed',
  'intel',
  'review'],
 ['russia', 'say', 'u', 'providing', 'cover', 'islamic', 'state', 'syria'],
 ['u', 'weakens', 'retirement', 'advice', 'rule', 'responding', 'industry'],
 ['grief',
  'stricken',
  'family',
  'japanese',
  'abducted',
  'north',
  'korea',
  'pin',
  'hope',
  'trump'],
 ['trump', 'say', 'likely', 'sign', 'healthcare', 'order', 'week'],
 ['bill', 'reilly', 'fox', 'news', 'alleged', 'sexual', 'remark'],
 ['professional',
  'panderer',
  'carly',
  'fiorina',
  'say',
  'ted',
  'cruz',
  'say',
  'anything',
  'get',
  'elected',
  'video'],
 ['2',
  'house',
  'republican',
  'say',
  'healthcare',
  'bill',
  'debate',
  'start',
  'friday',
  'cnn'],
 ['sean', 'hannity', 'go', 'apesh', 'trump', 'caesar'],
 ['development',
  'aid',
  'cannot',
  'part',
  'defense',
  'spending',
  'nato',
  'stoltenberg'],
 ['sound',
  'detected',
  'missing',
  'argentine',
  'submarine',
  'navy',
  'spokesman'],
 ['facebook',
  'say',
  'likely',
  'russian',
  'based',
  'operation',
  'funded',
  'u',
  'ad',
  'political',
  'message'],
 ['trump', 'skip', 'debate', 'win', 'social', 'medium'],
 ['obama', 'speaks', 'protester', 'derided', 'trump'],
 ['liberal',
  'american',
  'woman',
  'hot',
  'water',
  'attack',
  'danish',
  'man',
  'wearing',
  'maga',
  'hat',
  'denmark',
  'video'],
 ['factbox', 'catalonia', 'crisis', 'next'],
 ['french',
  'minister',
  'say',
  'u',
  'energy',
  'secretary',
  'ha',
  'signaled',
  'climate',
  'backpedalling'],
 ['powerful',
  'black',
  'trump',
  'supporter',
  'give',
  'msnbc',
  'reporter',
  'huge',
  'dose',
  'truth',
  'video'],
 ['cnn',
  'host',
  'abruptly',
  'end',
  'segment',
  'fox',
  'sport',
  'guest',
  'make',
  'disgusting',
  'trump',
  'like',
  'comment',
  'video'],
 ['icelandic',
  'party',
  'left',
  'right',
  'begin',
  'formal',
  'coalition',
  'talk'],
 ['comedy',
  'gold',
  'left',
  'go',
  'bonkers',
  'trump',
  'withdrawal',
  'paris',
  'accord',
  'video'],
 ['russian', 'bomber', 'strike', 'islamic', 'state', 'target', 'syria', 'ria'],
 ['russian', 'lawmaker', 'approve', 'foreign', 'agent', 'medium', 'law'],
 ['new',
  'hampshire',
  'governor',
  'asks',
  'trump',
  'stop',
  'indonesian',
  'deportation',
  'effort'],
 ['south',
  'carolina',
  'remove',
  'confederate',
  'flag',
  'boehner',
  'call',
  'review',
  'flag',
  'issue'],
 ['white',
  'house',
  'say',
  'fbi',
  'director',
  'trying',
  'influence',
  'election'],
 ['ammosexual',
  'anti',
  'obama',
  'organizer',
  'shoot',
  'fellow',
  'patriot',
  'drunken',
  'fight',
  'gun',
  'video',
  'screenshots'],
 ['msnbc',
  'reporter',
  'shocked',
  'leftist',
  'call',
  'firing',
  'pointing',
  'trump',
  'genuine',
  'compassion',
  'tx',
  'flood',
  'victim',
  'grandpa',
  'public',
  'never',
  'see'],
 ['rosie',
  'donnell',
  'get',
  'tongue',
  'lashing',
  'attack',
  'barron',
  'trump',
  'worry',
  'child'],
 ['trade', 'critic', 'trump', 'visit', 'boeing', 'co', 'backyard'],
 ['u',
  'slated',
  'sell',
  '375',
  'million',
  'emergency',
  'reserve',
  'oil',
  'winter'],
 ['ted',
  'nugent',
  'latest',
  'racist',
  'rant',
  'may',
  'cost',
  'one',
  'thing',
  'love'],
 ['obama', 'already', 'winning', 'war', 'replace', 'scalia'],
 ['texas',
  'super',
  'dolt',
  'louie',
  'gohmert',
  'savaged',
  'licking',
  'trump',
  'boot',
  'london',
  'response',
  'tweet'],
 ['ouch',
  'paul',
  'joseph',
  'watson',
  'destroys',
  'mtv',
  'racist',
  'propaganda',
  'video',
  'beyonce',
  'care',
  'much',
  'black',
  'issue',
  'dye',
  'hair',
  'blonde',
  'bleach',
  'skin',
  'try',
  'look',
  'white',
  'possible',
  'video'],
 ['trump', 'becoming', 'chris', 'christie', 'sugar', 'daddy'],
 ['german',
  'justice',
  'minister',
  'say',
  'thing',
  'get',
  'crazy',
  'trump',
  'win'],
 ['terrorist',
  'inspired',
  'dallas',
  'cop',
  'killer',
  'must',
  'kill',
  'white',
  'police',
  'officer',
  'across',
  'country',
  'asking',
  'black',
  'police',
  'officer',
  'take',
  'leave',
  'absence'],
 ['confidence',
  'vote',
  'pennsylvania',
  'approved',
  'amid',
  'corruption',
  'probe'],
 ['bernie',
  'sander',
  'supporter',
  'need',
  'support',
  'progressive',
  'candidate'],
 ['china',
  'state',
  'medium',
  'warn',
  'trump',
  'renouncing',
  'free',
  'trade',
  'deal'],
 ['gop',
  'candidate',
  'love',
  'trump',
  'put',
  'self',
  'righteous',
  'f',
  'ggots',
  'place'],
 ['trump', 'tweet', 'deranged'],
 ['house',
  'republican',
  'group',
  'move',
  'impeach',
  'irs',
  'chief',
  'politico'],
 ['wilbur', 'ross', 'seen', 'trump', 'pick', 'commerce', 'department', 'wsj'],
 ['trump',
  'campaign',
  'manager',
  'accused',
  'assaulting',
  'female',
  'reporter',
  'tweet'],
 ['female',
  'cab',
  'driver',
  'entering',
  'mandalay',
  'bay',
  'casino',
  'property',
  'record',
  'video',
  'appears',
  'capture',
  'gun',
  'fire',
  'one',
  'location'],
 ['obama', 'call', 'update', 'government', 'protect', 'american'],
 ['exclusive',
  'australia',
  'u',
  'refugee',
  'swap',
  'doubt',
  'official',
  'exit',
  'nauru'],
 ['german', 'police', 'say', 'potsdam', 'explosive', 'package', 'terrorism'],
 ['loretta',
  'lynch',
  'behavior',
  '2016',
  'election',

In [ ]:
# Initialize the Tfidf vectorizer
X_train_tf = tfidf_vectorizer.fit_transform([' '.join(i) for i in X_train])
X_test_tf = tfidf_vectorizer.transform([' '.join(i) for i in X_test])

In [27]:
# Initialize the Random Forest Classifier
rf_classifier2 = RandomForestClassifier()

# Train the classifier on the training data
rf_classifier2.fit(X_train_tf, y_train)

RandomForestClassifier()

In [28]:
# Make predictions on the test data
y_test_pred2 = rf_classifier2.predict(X_test_tf)
print("Training Data Classification Report:")
print(classification_report(y_test, y_test_pred2))
print("Training Data Accuracy Score:", accuracy_score(y_test, y_test_pred2))

Training Data Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3529
           1       0.91      0.91      0.91      3302

    accuracy                           0.91      6831
   macro avg       0.91      0.91      0.91      6831
weighted avg       0.91      0.91      0.91      6831

Training Data Accuracy Score: 0.9148001756697409

In [29]:
import gensim # topic modeling
import gensim.downloader as api # download pre-trained models

In [30]:
model_new = api.load("word2vec-google-news-300")

In [31]:
# Check if the model is loaded
print(model_new)

KeyedVectors<vector_size=300, 3000000 keys>

In [32]:
# Convert text data to numerical features using Word2Vec for X_train and X_test
def get_word2vec_vector(text):
    if isinstance(text, list):  # If the text is a list, join it into a single string
        text = ' '.join(text)
    words = text.split()
    word_vectors = []
    for word in words:
        try:
            word_vectors.append(model_new[word])
        except KeyError:
            continue
    if len(word_vectors) == 0:
        return np.zeros(model_new.vector_size)
    else:
        return np.mean(word_vectors, axis=0)
import numpy as np
X_train_word2vec = np.array([get_word2vec_vector(text) for text in X_train])
X_test_word2vec = np.array([get_word2vec_vector(text) for text in X_test])
# Initialize the Random Forest Classifier
rf_classifier3 = RandomForestClassifier()
# Train the classifier on the training data
rf_classifier3.fit(X_train_word2vec, y_train)
# Make predictions on the test data
y_test_pred3 = rf_classifier3.predict(X_test_word2vec)
print("Training Data Classification Report:")
print(classification_report(y_test, y_test_pred3))
print("Training Data Accuracy Score:", accuracy_score(y_test, y_test_pred3))

Training Data Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.88      0.89      3529
           1       0.88      0.89      0.88      3302

    accuracy                           0.89      6831
   macro avg       0.89      0.89      0.89      6831
weighted avg       0.89      0.89      0.89      6831

Training Data Accuracy Score: 0.886253842775582

In [11]:
test_data = pd.read_csv('testing_data.csv')

In [19]:
columns = ['label', 'headline']
test_data = pd.read_csv('testing_data.csv', sep='\t', header=None, names=columns)

print(test_data.head())

  label                                           headline
0     2  copycat muslim terrorist arrested with assault...
1     2  wow! chicago protester caught on camera admits...
2     2   germany's fdp look to fill schaeuble's big shoes
3     2  mi school sends welcome back packet warning ki...
4     2  u.n. seeks 'massive' aid boost amid rohingya '...

In [20]:
X_new = test_data['headline']

In [21]:
# Ensure the text data is transformed into numerical features using the TfidfVectorizer
X_new_tfidf = tfidf_vectorizer.transform(X_new)
# Make predictions using the Random Forest Classifier
prediction = rf_classifier.predict(X_new_tfidf)

In [22]:
test_data['prediction'] = prediction

In [23]:
test_data.head(20)

   label                                           headline  prediction
0      2  copycat muslim terrorist arrested with assault...           0
1      2  wow! chicago protester caught on camera admits...           0
2      2   germany's fdp look to fill schaeuble's big shoes           1
3      2  mi school sends welcome back packet warning ki...           0
4      2  u.n. seeks 'massive' aid boost amid rohingya '...           1
5      2  did oprah just leave ‚nasty‚ hillary wishing s...           0
6      2  france's macron says his job not 'cool' cites ...           1
7      2  flashback: chilling ‚60 minutes‚ interview wit...           0
8      2  spanish foreign ministry says to expel north k...           1
9      2  trump says cuba 'did some bad things' aimed at...           1
10     2  merkel names refugee expert as foreign policy ...           1
11     2  brazil house speaker says temer charges must b...           1
12     2  finger in every pie: how cia produces our ‚new...           0
13     2  how malia obama‚s pot smoking friend is connec...           0
14     2  no-one can wreck our democracy schaueble tells...           0
15     2  media ignores post on facebook from man who th...           0
16     2  left-wing author blasts democrats for ‚scandal...           0
17     2  revealed: how democratic party pays agit-prop ...           0
18     2  macron calls for french food chain changes to ...           1
19     2  breaking news: gop controlled house votes to r...           0